### ISSUE TITLE
Use BigFloat instead of error plateau heuristic in linsolve?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/ApproxFun.jl#125]
Some operators (mostly with singular points) have solutions that "plateau" at round off error, so there is a scattering of adhoc choices of tolerance.

Using BigFloats for the solution would probably cause the plateau point to go well below machine eps, so the tolerance would not have to be tuned so carefully.  I think this should be true even if the operator is created with floats.  

Is this better than adhoc tolerances?

**Comment by MikaelSlevinsky** [comment]
MPFR is used to compute literal constants more accurately at compile time. This sounds like a generalization of this idea for `Fun`s.

Here's an instance from #121 that supports this idea:

```julia
x = Fun(identity,[1e2,1e4])
f = besselj0(x)
g = Fun(besselj0,[1e2,1e4])
xBig = Fun(identity,Interval{BigFloat}(1e2,1e4))
hBig = besselj0(xBig)
h = Fun(float64(hBig.coefficients)[1:length(f)],space(x))
length(f),length(g),length(h)
f[500]-besselj0(500),g[500]-besselj0(500),h[500]-besselj0(500)
hBig[big(500.0)]-besselj0(big(500.0))
```

I didn't investigate why exactly it's slow, but the accuracy is correct.
