### ISSUE TITLE
Element types of RealBasis & ComplexBasis

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaApproximation/ApproxFun.jl#155]
It seems a little too specific to say they're `Float64` or `Complex{Float64}`. If they were `FloatingPoint` and `Complex{FloatingPoint}`, a `concrete_type(a,b)`, which would be a weird combination of demoting an abstract type and promoting another concrete type if necessary, could be used. For instance:

``` julia
concrete_type(::Type{FloatingPoint},::Type{BigFloat}) = BigFloat
concrete_type(::Type{FloatingPoint},::Type{Float64}) = Float64
concrete_type(::Type{FloatingPoint},::Type{Float32}) = Float32
concrete_type(::Type{FloatingPoint},::Type{Float16}) = Float16

concrete_type(::Type{FloatingPoint},::Type{BigInt}) = BigFloat
concrete_type(::Type{FloatingPoint},::Type{Int128}) = Float64
concrete_type(::Type{FloatingPoint},::Type{Int64}) = Float64
concrete_type(::Type{FloatingPoint},::Type{Int32}) = Float32
concrete_type(::Type{FloatingPoint},::Type{Int16}) = Float16
concrete_type(::Type{FloatingPoint},::Type{Int8}) = Float16
```

**Comment by dlfivefifty** [comment]
That was just a quick decision to get RealBasis/ComplexBasis working.  

	My feeling is that we should put off any structural changes until 0.4, when we have a bit more flexibility to make changes.  E.g., adding type/domain information to FunctionSpace.  (This is postponed til 0.4 because 0.3 doesn’t allow typealias/abstract types as constructors.)

**Comment by MikaelSlevinsky** [comment]
I think this can be fixed quite easily with promotion rules between basis types and number types. Then, wherever there was an `eltype(::FunctionSpace)`, we replace that with the `basistype(::FunctionSpace)` and the type promotion should be good from there.

**Comment by dlfivefifty** [comment]
RealBasis & ComplexBasis no longer exist!
