### ISSUE TITLE
Should WeightSpace be a concrete type that takes a Tuple of Weights?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/ApproxFun.jl#204]
Then there would a LeftJacobiWeight, RightJacobiWeight, and what's currently JacobiWeight becomes 

WeightSpace((LeftJacobiWeight(α),RightJacobiWeight(β)))

This would then supports mixed weights, e.g., LeftJacobiWeight(α) and FourierWeight(ω) to represent (1+x)^α_exp(im_ω*x)

The drawback is getting to the parameters becomes harder, though what could happen is S.α becomes parameter(S,1)

**Comment by MikaelSlevinsky** [comment]
Since ⊗ is taken for `TensorSpace`, perhaps ⊙ could be used for stacking `WeightSpace`s of the same dimensions. I have to think about Left\Right JW. Seems kinda bureaucratic but if it's the only way that works...
