### ISSUE TITLE
MultiplicationWrapper doubles the data

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaApproximation/ApproxFun.jl#249]
MultiplicationWrapper takes f::Fun, and op::BandedOperator. Almost everywhere, op is a SpaceOperator which has a Multiplication operator with the original f and a different space.

One possibility is if a Multiplication operator had a domainspace and a rangespace, then most of the cases could be handled without SpaceOperator or MultiplicationWrapper and only one copy of f.

**Comment by dlfivefifty** [comment]
It doesn't actually double the data since it's pointers to the same object.
