### ISSUE TITLE
Rethink evaluate{D<:SumSpace,T}(f::Fun{D,T},x)

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaApproximation/ApproxFun.jl#261]
Seemingly few allocations (~100) can accumulate to the millions in, for example, the low rank function constructor.

This explains this difference:

``` julia
julia> using ApproxFun

julia> f(x,y) = besselj0(100abs(y-x));sp1 = Chebyshev()⊗Chebyshev();sp2 = Laurent(Circle())⊗Laurent(Circle());

julia> @time LowRankFun(f,sp1;method=:Cholesky,maxrank=400);
  0.020670 seconds (80.16 k allocations: 19.542 MB, 17.70% gc time)

julia> @time LowRankFun(f,sp2;method=:Cholesky,maxrank=400);
  1.245531 seconds (4.59 M allocations: 1001.034 MB, 12.37% gc time)
```

We should reasonably expect the low-rank Laurent series to take on-the-same-order of time.

**Comment by MikaelSlevinsky** [comment]
this also afflicts `PiecewiseSpace`

**Comment by dlfivefifty** [comment]
I think https://github.com/JuliaApproximation/ApproxFun.jl/issues/491 with coefficient views should help here.

**Comment by dlfivefifty** [comment]
I got it down to only 2 allocations, for 2 component views!
```julia
x=Fun()

f=sin(100x)*sqrt(1+x)+cos(100000x)
@btime ($f)(0.1)   # 545.239 μs (2 allocations: 128 bytes)
```

**Comment by dlfivefifty** [comment]
That is, creating a `SubArray` via `view` counts as an allocation. Supposedly, this too will be gone soon.

**Comment by dlfivefifty** [comment]
Your example has been reduced to
```julia
julia> @time LowRankFun(f,sp2;method=:Cholesky,maxrank=400);
  0.577044 seconds (2.48 M allocations: 660.057 MiB, 22.21% gc time)
```
It's a silly comparison though since the ranks aren't comparable:
```julia
julia> rank(LowRankFun(f,sp1;method=:Cholesky,maxrank=400))
80

julia> rank(LowRankFun(f,sp2;method=:Cholesky,maxrank=400))
259
```
