### ISSUE TITLE
Functional*Fun should return a Fun([x],ConstantSpace())

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/ApproxFun.jl#350]
The latter has the benefit of consistency with Operator*Fun.

**Comment by MikaelSlevinsky** [comment]
This is somehow related to the ambiguity that arises in defining a `UnionDomain` of a single `Domain` #274.

**Comment by dlfivefifty** [comment]
I think we should return `Fun([2.3],ConstantSpace(D))` but make show display it as `2.3 on D`.  

This should work find since `Number(Fun([2.3],ConstantSpace(D))` returns 2.3, so a user can treat `2.3 on D` like its `2.3`.

**Comment by dlfivefifty** [comment]
This just triggered a bug.

**Comment by MikaelSlevinsky** [comment]
It may have to do with the salvaged PR.

**Comment by dlfivefifty** [comment]
It was actually two problems: Operator*Number was returning an Operator, so I've changed it so that Operator*Number is now consistent with Operator*Fun and returns a Fun.  This avoids having to change this for now.

It was caused by a TimesOperator that was A = Operator * Functional * Operator .  So A*f would end up with Operator * Number.

**Comment by dlfivefifty** [comment]
The Salvaged PR only triggered a bug that was there already.
