### ISSUE TITLE
rename org  to JuliaApprox or JuliaApproxFun  ?

### ISSUE THREAD

**Issue by musm** [JuliaApproximation/ApproxFun.jl#386]
http://julialang.org/community/

Would be nice to have an org related to all approximation type work consistent with the other Julia communities. 

Thoughts?

**Comment by dlfivefifty** [comment]
I think this is a reasonable idea. I'd be happy with either JuliaApproximation or JuliaSpectral.

In this case it would also make sense to move out some of the projects that are here because they depend on ApproxFun.

**Comment by musm** [comment]
JuliaApproximation 
might be better as it could contain a wider array of function approximation packages, i.e. packages implementing remez, minimax methods and other related algorithms of interest? 

> In this case it would also make sense to move out some of the projects that are here because they depend on ApproxFun. 👍 

It would also then make sense to org under the community heading on the webpage for wider exposure.

**Comment by MikaelSlevinsky** [comment]
For future reference, (rational) remez in BigFloat exists here: https://github.com/simonbyrne/Remez.jl, and has a PR for conversion to Chebyshev bases.

**Comment by dlfivefifty** [comment]
I'm going to wait until I tag the next release of ApproxFun before making this change.

**Comment by simonbyrne** [comment]
I would be keen to integrate Remez.jl with ApproxFun: I did spend a bit of time trying to figure it out, but the lack of documentation did make it difficult (though admittedly, Remez.jl isn't that well documented either). 

FWIW: I don't think the name of the org matters that much, and it is quite easy to rename at a later date (unlike packages).

**Comment by dlfivefifty** [comment]
Remez.jl just returns Taylor coefficients, correct?  You could do

```
cfs = #calculate taylor coeffs using Remez
f=Fun(cfs,Taylor())
```


Sorry about the lack of documentation: this is partly on purpose as a lot of the design is experimental and is likely to change, and so I don't want to encourage users.   It's starting to settle in on a design now, however, and so I may add more documentation.

**Comment by MikaelSlevinsky** [comment]
My pull request would have Remez return Chebyshev coefficients.

Simon and I discussed integration with ApproxFun so that `remez` invoked with a `Chebyshev` space on an `Interval` gives the classic Remez algorithm, and when it's invoked with a `Taylor` space on a `PeriodicInterval` it gives best trig approximation.

It would also be possible to have `remez` return Taylor coefficients on a regular interval, though these coefficients are ill-conditioned.
