### ISSUE TITLE
Setting up a Neumann boundary condition from a known 2D function

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaApproximation/ApproxFun.jl#417]
dlfivefify kindly showed us how to set up a Dirichlet boundary condition on a rectangle from a know 2D function and solve, say, the Helmholtz equation, for the current tagged ApproxFun:
```
julia> D = Interval()^2 # The domain is [-1,1]x[-1,1].
julia> \Delta = Laplacian(D)
julia> g = Fun((x,y)->cos(5pi*x+7pi*y)) # an example 2D function on D
julia> f = Fun(z->(x=real(z);y=imag(z);g(x,y)),\partial(D)) # boundary values of g
julia> u = [dirichlet(D); \Delta + 500I] \ [f; 0.0]
```
This is beautiful and dandy. But how can I use the Neumann boundary condition using the normal derivatives of ```g``` at the boundary ```\partial(D)```?
Obviously, the last line above should be replaced by:
```
julia> u = [neumann(D); \Delta + 500I] \ [f; 0.0]
```
But how can I specify the correct Neumann boundary value function ```f``` ?
Thanks a lot for your help!
BVPs

**Comment by dlfivefifty** [comment]
This should work:
```julia
d=Interval()^2
Δ=Laplacian(d)
u=[neumann(d);Δ+100I]\[ones(∂(d));0.0]
plot(u)
```

**Comment by BoundaryValueProblems** [comment]
Sorry, my question was perhaps not clear. I know how to set up the Neumann boundary condition in that case, i.e., the normal derivative is 1 (or some other constant) at the boundary as you listed. What I want to do is to compute the normal derivative at the boundary of a given non-constant function g(x,y), and set those normal derivative values as the Neumann boundary condition.
Best,
BVPs

**Comment by dlfivefifty** [comment]
Try

	neumann()*g

though this may not work.  If not, try:

	[neumann()[1]*g;neumann()[2]*g;neumann()[3]*g;neumann()[4]*g]

Handling Neumann conditions elegantly is not yet done, nor is it clear to me how best to do it.  The current usage of “neumann” may be a misnomer, since the normal derivative on the left/bottom has the wrong sign I think.

**Comment by BoundaryValueProblems** [comment]
Thanks, dlfivefifty. I tried both, but neither works under the tagged ApproxFun.jl (version 0.3.3). Each of them generates the following error:
> MethodError: no method matching ApproxFun.Evaluation{T}(::Type{Float64}, ::ApproxFun.TensorSpace{Tuple{ApproxFun.Chebyshev{ApproxFun.Interval{Float64}},ApproxFun.Chebyshev{ApproxFun.Interval{Float64}}},ApproxFun.RealBasis,2}, ::Bool, ::Int64)
Closest candidates are:
  ApproxFun.Evaluation{T}{T}(::Type{T}, !Matched::ApproxFun.Space{T,D,1}, ::Bool, ::Integer) at /Users/xxx/.julia/v0.5/ApproxFun/src/Operators/functionals/Evaluation.jl:15
  ApproxFun.Evaluation{T}{T}(::Type{T}, !Matched::ApproxFun.Space{T,D,1}, ::Number, ::Integer) at /Users/xxx/.julia/v0.5/ApproxFun/src/Operators/functionals/Evaluation.jl:18
  ApproxFun.Evaluation{T}{T<:ApproxFun.IntervalDomain{T}}(!Matched::Array{T<:ApproxFun.IntervalDomain,1}, ::Any...) at /Users/xxx/.julia/v0.5/ApproxFun/src/Operators/systems.jl:21
  ...
 in *(::ApproxFun.ConcreteEvaluation{ApproxFun.UnsetSpace,Bool,Int64,ApproxFun.UnsetNumber}, ::ApproxFun.Fun{ApproxFun.TensorSpace{Tuple{ApproxFun.Chebyshev{ApproxFun.Interval{Float64}},ApproxFun...

**Comment by dlfivefifty** [comment]
Try `neumann(space(g))` instead of `neumann()`

**Comment by BoundaryValueProblems** [comment]
OK, I first tried:
```
julia> f = neumann(space(g))*g
```
to set up the boundary condition as ```f```. Then, the above command generated the following error:
v StackOverflowError:
in next at ApproxFun/src/Multivariate/TensorSpace.jl:43
in next at ApproxFun/src/Multivariate/TensorSpace.jl:39
...
fatal: error thrown and no exception handler available.
ErrorException("task switch not allowed from inside gc finalizer")
rec_backtrace at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/stackwalk.c:84
...

Second, if I use:
```
julia> f = neumann(space(g))
```
that line does not generate any error, and intead it displays:
KroneckerOperator:Chebyshev(【-1.0,1.0】)⊗ApproxFun.UnsetSpace()↦ConstantSpace(Point(-1.0))⊗ApproxFun.UnsetSpace()
KroneckerOperator:Chebyshev(【-1.0,1.0】)⊗ApproxFun.UnsetSpace()↦ConstantSpace(Point(1.0))⊗ApproxFun.UnsetSpace()
KroneckerOperator:ApproxFun.UnsetSpace()⊗Chebyshev(【-1.0,1.0】)↦ApproxFun.UnsetSpace()⊗ConstantSpace(Point(-1.0))
KroneckerOperator:ApproxFun.UnsetSpace()⊗Chebyshev(【-1.0,1.0】)↦ApproxFun.UnsetSpace()⊗ConstantSpace(Point(1.0))

But, when I try to solve, say the Laplace equation:
```
julia> u = [ neumann(D); Δ]\[f;0.0]
```
the following error is generated:
v MethodError: objects of type ApproxFun.KroneckerOperator{ApproxFun.ConcreteEvaluation{ApproxFun.Chebyshev{ApproxFun.Interval{Float64}},Bool,Int64,Float64},ApproxFun.ConstantOperator{Float64,ApproxFun.UnsetSpace},ApproxFun.TensorSpace{Tuple{ApproxFun.Chebyshev{ApproxFun.Interval{Float64}},ApproxFun.UnsetSpace},ApproxFun.RealBasis,2},ApproxFun.TensorSpace{Tuple{ApproxFun.ConstantSpace{ApproxFun.Point{Float64}},ApproxFun.UnsetSpace},ApproxFun.RealBasis,2},ApproxFun.CachedIterator{Tuple{Int64,Int64},ApproxFun.TensorIterator{Tuple{ApproxFun.Infinity{Bool},ApproxFun.Infinity{Bool}}},Tuple{Int64,Int64}},ApproxFun.CachedIterator{Tuple{Int64,Int64},ApproxFun.TensorIterator{Tuple{Int64,ApproxFun.Infinity{Bool}}},Tuple{Int64,Int64}},Float64} are not callable
 in zerocfsFun(::ApproxFun.##46#47{ApproxFun.KroneckerOperator{ApproxFun.ConcreteEvaluation{ApproxFun.Chebyshev{ApproxFun.Interval{Float64}},Bool,Int64,Float64},ApproxFun.ConstantOperator{Float64,ApproxFun.UnsetSpace},ApproxFun.TensorSpace{Tu...

So, something is still wrong.
Best,
BVPs

**Comment by dlfivefifty** [comment]
This works for me on development:

```julia
d=Interval()^2
f=Fun((x,y)->exp(x)*cos(y),d)
B=neumann(d)
Δ=Laplacian(d)
@time u=linsolve([B;Δ+10I],[neumann(d)*f;(Δ+10I)*f];tolerance=1E-12)
norm((u-f).coefficients)
```

Note that `[ neumann(D); Δ]` is non-invertible: the function `u(x,y) = 1` is in the kernel.

**Comment by BoundaryValueProblems** [comment]
Hello. OK, I installed the development version of ApproxFun.jl, and conducted the following experiment, i.e., the Helmholtz equation with the Neumann boundary condition. I wanted to check if we get the correct solution, so I set up the following problem:
```
julia> d=Interval()^2
julia> Δ=Laplacian(d)
julia> g=Fun((x,y)->cos(5pi*x)*cos(7pi*y),d)  # We know that Δg = -(74pi^2)g.
julia> B=neumann(d)
julia> f=B*g # This should compute the normal derivative of g on the domain d, and set it as f.
julia> u=linsolve([B;Δ+(74pi^2)I], [f;0.0]; tolerance=1E-12) # u should be the same as g modulo global constants.
```
Now, I could get ```u``` without error, but
```
julia> norm(u.coefficients)
6.37e-14
```
that is, practically, 0 function while
```
julia> norm(g.coefficients)
1.08
```
In other words, ```u``` did not recover ```g```. I'm curious what went wrong here. Maybe because ```g``` is a Neumann-eigenfunction of ```Δ+(74pi^2)I```, so I need to view it modulo a constant multiplication? I tried to compute ```g-u/u[1,1]``` and ```g-u/maximum(u)```, but these are non-negligible. So, I also tried to avoid the eigenfunction computation and changed the operator to ```Δ+(74pi^2-0.1)I```. But the results are more or less the same.
What went wrong here?

Also, I have another question: ```contourf(u)``` does not work while ```contourf(g)``` works without any problem. The former generated the following error:
```
BoundsError: attempt to access 146-element Array{ApproxFun.Fun{ApproxFun.Chebyshev{ApproxFun.Interval{Float64}},Float64},1} at index [0]
 in chop(::ApproxFun.ProductFun{ApproxFun.Chebyshev{ApproxFun.Interval{Float64}},ApproxFun.Chebyshev{ApproxFun.Interval{Float64}},ApproxFun.TensorSpace{Tuple{ApproxFun.Chebyshev{ApproxFun.Interval{Float64}},ApproxFun.Chebyshev{ApproxFun.Interval{Float64}}},ApproxFun.RealBasis,ApproxFun.ProductDomain{Tuple{ApproxFun.Interval{Float64},ApproxFun.Interval{Float64}},Float64,2},2},Float64}, ::Float64) at /Users/xxx/.julia/v0.5/ApproxFun/src/Multivariate/ProductFun.jl:215
 in macro expansion at /Users/xxx/.julia/v0.5/ApproxFun/src/Plot/Plot.jl:267 [inlined]
 in apply_recipe(::Dict{Symbol,Any}, ::ApproxFun.ProductFun{ApproxFun.Chebyshev{ApproxFun.Interval{Float64}},ApproxFun.Chebyshev{ApproxFun.Interval{Float64}},ApproxFun.TensorSpace{Tuple{ApproxFun.Chebyshev{ApproxFun.Interval{Float64}},ApproxFun.Chebyshev{ApproxFun.Interval{Float64}}},ApproxFun.RealBas...
```
With the Dirichlet boundary condition under the tagged released version of ApproxFun.jl, ```contourf(real(u))``` worked without any problem (although I had to use ```real(u)``` because that version returns the complex-valued array).

Thanks for your help on these issues!
BVPs

**Comment by dlfivefifty** [comment]
The equation is ill posed at eigenvalues

**Comment by BoundaryValueProblems** [comment]
Yes, I know. But then I have two questions:
(1) As I said earlier, I perturbed the eigenvalue slightly (in the above example, ```74pi^2-0.1``` instead of ```74pi^2```) so that the system shouldn't be ill-posed. Yet, I got the essentially trivial solution (close to 0) as in the exact eigenvalue case. Why does this happen?
(2) Is there any method implemented in ApproxFun.jl to compute the Dirichlet-Laplacian eigenvalues/eigenfunctions on a 2D rectangular domain?
Thanks!
BVPs

**Comment by dlfivefifty** [comment]
B*g is zero on the boundary, I'm not sure what you are expecting but u=0 is indeed the solution to `[B;Δ+(74π^2-0.1)*I] \ 0`

**Comment by dlfivefifty** [comment]
(2) for ODEs, you have `eigvals([B;Δ],100)`.  This doesn't work for PDEs. You can do inverse iteration though pretty efficiently:

```julia
QR=qrfact([B;Δ+9.0I])

u=linsolve(QR,[zeros(4);Fun(rand(5),d)];tolerance=1E-6)

for k=1:20
    u=linsolve(QR,[zeros(4);u];tolerance=1E-6)
    u=chop(u/norm(u.coefficients),1E-15)
end

norm((Δ*u+π^2*u).coefficients)  # 1E-13
```

**Comment by dlfivefifty** [comment]
Ideally, `eigvals` would be overwritten to do simultaneous inverse iteration with Wilkinson shift, instead of the current approach resorting to matrix `eigvals`.  I don't have time to work on that at the moment, however.

**Comment by BoundaryValueProblems** [comment]
You are absolutely correct. I just didn't realize that I had set the zero Neumann condition.
Now, instead of that ```g```, I changed it to ```g=Fun((x,y)->sin(5π*x)*sin(7π*y),D)``` so that the Neumann boundary values are nonzeros.  Then, with the ill-posed system: ```u=linsolve([B;Δ+(74π^2)*I], [B*g;0.0];tolerance=1E-12)```, I got a reasonable result although the solution of the perturbed problem: ```u2=linsolve([B;Δ+(74π^2-0.1)*I], [B*g;0.0];tolerance=1E-12)``` gave me a closer approximation to ```g```.
Thanks!
BVPs
