### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by dpsanders** [JuliaApproximation/ApproxFun.jl#438]
Clicking on the documentation link leads to a non-existent webpage at

http://approxfun.github.io/

**Comment by dlfivefifty** [comment]
Fixed!

**Comment by dpsanders** [comment]
Great, thanks!

**Comment by dlfivefifty** [comment]
Any suggestions on the docs would be greatly appreciated.  It's fairly minimal at the moment.
