### ISSUE TITLE
Double roots sometimes missed

### ISSUE THREAD

**Issue by dpsanders** [JuliaApproximation/ApproxFun.jl#447]
Double roots are sometimes missed, even though the colleague matrix eigenvalues are correctly found.

```julia
julia> a = 2; f = Fun(x -> (x^2-2)^2, -a..a); roots(f)
2-element Array{Float64,1}:
 1.41421
 1.41421

julia> eigvals(ApproxFun.colleague_matrix(f.coefficients))
4-element Array{Complex{Float64},1}:
 -0.707107+6.89931e-9im
 -0.707107-6.89931e-9im
           0.707107+0.0im
           0.707107+0.0im
```

**Comment by dpsanders** [comment]
This may just be a problem with the tolerance on the imaginary part?

**Comment by dlfivefifty** [comment]
It looks like it.  The tolerance on the complex part has not been thought through. `complexroots` gives all the roots.

At the moment, its using LAPACKs upper hessenberg `eigvals`, with an adhoc column balancing.  Using dense `eigvals` sometimes performs better as that does LAPACKs inbuilt column balancing for you.  I never figured out how to access this.

Another option is to switch to AVWM.jl, but that is slower at small dimensions, and `roots` for `Chebyshev` only needs to deal with low degree roots as it auto-subdivides

**Comment by ajt60gaibb** [comment]
It is perfectly reasonable for a numerically stable polynomial rootfinder to miss a double root.  Just from perturbing the original polynomial, a stable rootfinder on the example above can either return two simple roots or miss the double root entirely.    If you change the tolerance on the complex part for masking, then the rootfinder will start to project more imaginary roots onto the real line. 

Missing double roots like this is a consequence of working in floating point arithmetic.

**Comment by dlfivefifty** [comment]
I guess it would become reasonable if you use interval arithmetic: that is, you look for the set of all x such that f(x) is within eps of 0.

@dpsanders and I were talking about incorporating interval arithmetic in ApproxFun to get rigorous calculations.

**Comment by MikaelSlevinsky** [comment]
Does the balancing scale only by powers of 2? This would ensure that no rounding errors (provided coefficients are not near the type min/max) pollute the colleague matrix before passing it to an upper-Hessenberg `eigvals`

**Comment by dlfivefifty** [comment]
The scaling I used was completely ad hoc: I just tried something and it fixed a bug. LAPACK has its own scaling for general eigenvalue problems which would be much better to yse, but not one that's exposed for Hessenberg matrices, as far as I can tell.
