### ISSUE TITLE
Chaining of evaluation and functions

### ISSUE THREAD

**Issue by natschil** [JuliaApproximation/ApproxFun.jl#451]
Does there exist a standard way of creating a linear operator T from a function space to itself (with DomainSpace X) of the form:

(T u)(x) = u(f(x))

where f is some "sufficiently nice" function X->X? In the finite case this would correspond to a matrix where the rows are evaluation functionals. 

Apologies if this is the wrong place to ask this; I can't find any information as to whether the github issues section of this project is also open to general questions or not.

**Comment by dlfivefifty** [comment]
@wormell isn't this related to your work on invariant measures?

**Comment by dlfivefifty** [comment]
PS perfectly fine to ask this here.  Other option is Gitter

**Comment by natschil** [comment]
Invariant measures are essentially what I would like to use this for, so if someone has done that in ApproxFun already I would be very interested in knowing what parts of the code I need to be looking at.

**Comment by wormell** [comment]
@natschil Yes, I've got a package that does this stuff (and a heap of associated theory that is in the process of being written up for publication). It's geared towards transfer operators of Markov uniformly expanding maps in 1D but could easily be modified to do/may already support other things involving function composition if you need. Send me an email and we can talk! :)
