### ISSUE TITLE
Precompilation doesn't work with versions of Plots 0.10.0 and up

### ISSUE THREAD

**Issue by Pbellive** [JuliaApproximation/ApproxFun.jl#453]
Hi,
       Starting with version 0.10.0 `Plots` removed precompilation. I think this is because of julia 0.6 issues (see tbreloff/Plots.jl#545). Anyway, I installed `ApproxFun.jl` earlier today via `Pkg.add()` and when I tried to use it I got the following error:
```
julia> using ApproxFun
INFO: Precompiling module ApproxFun.
WARNING: Module Plots with uuid 251762207974442 is missing from the cache.
This may mean module Plots does not support precompilation but is imported by a module that does.
ERROR: LoadError: Declaring __precompile__(false) is not allowed in files that are being precompiled.
.
.
.
while loading /home/patrick/.julia/v0.5/ApproxFun/src/ApproxFun.jl, in expression starting on line 4
ERROR: Failed to precompile ApproxFun to /home/patrick/.julia/lib/v0.5/ApproxFun.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:422
```
This is on julia 0.5.1-pre+31. `using ApproxFun` returned without error when I commented out the `__precompile__()` line in `ApproxFun`. To confirm that the issue was caused by `Plots`, I rolled back my plots installation to v0.9.4 and uncommented the precompile line in ApproxFun. `using ApproxFun` then worked normally.

Not sure what the best way to handle this is but I thought I'd let you folks know. Looking forward to checking out your package now that I can load it!

**Comment by dlfivefifty** [comment]
I think the best way is to put an upper bound on Plots until precompile is restored, as compiling each time is going to be way too slow.

**Comment by dlfivefifty** [comment]
This should be fixed, I replaced the dependency on Plots with RecipesBase
