### ISSUE TITLE
Failure to import ApproxFun

### ISSUE THREAD

**Issue by orswan** [JuliaApproximation/ApproxFun.jl#457]
I just added the ApproxFun package, and upon trying to import it I get the following error:

    julia> import ApproxFun
    INFO: Precompiling module ApproxFun.
    ERROR: LoadError: Declaring __precompile__(false) is not allowed in files that are being precompiled.
     in __precompile__(::Bool) at .\loading.jl:300
     in include_from_node1(::String) at .\loading.jl:488
     in macro expansion; at .\none:2 [inlined]
     in anonymous at .\<missing>:?
     in eval(::Module, ::Any) at .\boot.jl:234
     in process_options(::Base.JLOptions) at .\client.jl:239
     in _start() at .\client.jl:318
    while loading C:\Users\swan\.julia\v0.5\Plots\src\Plots.jl, in expression starting on line 1
    ERROR: LoadError: Failed to precompile Plots to C:\Users\swan\.julia\lib\v0.5\Plots.ji.
     in compilecache(::String) at .\loading.jl:593
     in require(::Symbol) at .\loading.jl:393
     in include_from_node1(::String) at .\loading.jl:488
     in macro expansion; at .\none:2 [inlined]
     in anonymous at .\<missing>:?
     in eval(::Module, ::Any) at .\boot.jl:234
     in process_options(::Base.JLOptions) at .\client.jl:239
     in _start() at .\client.jl:318
    while loading C:\Users\swan\.julia\v0.5\ApproxFun\src\ApproxFun.jl, in expression starting on line 4
    ERROR: Failed to precompile ApproxFun to C:\Users\swan\.julia\lib\v0.5\ApproxFun.ji.
     in compilecache(::String) at .\loading.jl:593
     in require(::Symbol) at .\loading.jl:422

The error reported is not consistent.  Here's another trace:

    julia> import ApproxFun
    INFO: Precompiling module ApproxFun.
    WARNING: Module Plots with uuid 4861784595448007 is missing from the cache.
    This may mean module Plots does not support precompilation but is imported by a module that does.
    ERROR: LoadError: Declaring __precompile__(false) is not allowed in files that are being precompiled.
     in require(::Symbol) at .\loading.jl:385
     in include_from_node1(::String) at .\loading.jl:488
     in macro expansion; at .\none:2 [inlined]
     in anonymous at .\<missing>:?
     in eval(::Module, ::Any) at .\boot.jl:234
     in process_options(::Base.JLOptions) at .\client.jl:239
     in _start() at .\client.jl:318
    while loading C:\Users\swan\.julia\v0.5\ApproxFun\src\ApproxFun.jl, in expression starting on line 4
    ERROR: Failed to precompile ApproxFun to C:\Users\swan\.julia\lib\v0.5\ApproxFun.ji.
     in compilecache(::String) at .\loading.jl:593
     in require(::Symbol) at .\loading.jl:422

In case it's helpful, here is some output from `Pkg.status()`:

    julia> Pkg.status()
    ....
	 - ApproxFun                     0.4.1
	 - PlotRecipes                   0.2.0
	 - Plots                         0.10.3

**Comment by dlfivefifty** [comment]
This is a known problem with the new Plots.  I will tag a release shortly.  Until then, you need to to get an older version of Plots.

**Comment by orswan** [comment]
Thanks.  Do you know how much older a version of Plots?

**Comment by dlfivefifty** [comment]
The commit is https://github.com/tbreloff/Plots.jl/pull/554 on 2 Nov, see also https://github.com/tbreloff/Plots.jl/issues/545#issuecomment-272547627

I'm going to put an upper bound on the Plots for the existing tagged ApproxFun into METADATA which should automatically fix the issue.  I believe anything before Plots v0.10 is fine.

**Comment by dlfivefifty** [comment]
I made a pull request to METADATA to add upper bounds https://github.com/JuliaLang/METADATA.jl/pull/7584

**Comment by dlfivefifty** [comment]
I'll tag a new version of ApproxFun shortly
