### ISSUE TITLE
Document indexing on operators

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaApproximation/ApproxFun.jl#464]
The integral here introduces an indexing notation:

http://juliaapproximation.github.io/ApproxFun.jl/latest/usage/equations.html#Linear-equations-1

While it's understood by context, I think it should be mentioned on the previous page:

http://juliaapproximation.github.io/ApproxFun.jl/latest/usage/operators.html

**Comment by dlfivefifty** [comment]
I think this commit resolved this: https://github.com/JuliaApproximation/ApproxFun.jl/commit/fbfc1eb839a4b2c580149af55c6cce28088a8641

**Comment by dlfivefifty** [comment]
I'll add it to http://juliaapproximation.github.io/ApproxFun.jl/latest/usage/operators.html#Algebraic-manipulation-of-operators-1 as well

**Comment by ChrisRackauckas** [comment]
Oh hey. Thanks.
