### ISSUE TITLE
Pb of interactions between ApproxFun and Polynomials packages

### ISSUE THREAD

**Issue by edljk** [JuliaApproximation/ApproxFun.jl#466]
It seems that recent changes affected the ```LowRankFun``` constructor on julia  v0.5.1. The problem is related to the interaction with the ```Polynomials``` package (perhaps due to the roots functions) : 
```julia
using Polynomials, ApproxFun
d = PeriodicInterval(0,2*π)^2
LowRankFun(rand(4,4),Fourier(d[1]),Fourier(d[2]))

ERROR: + not defined for ApproxFun.Infinity{Bool}
 in mapfoldl_impl(::ApproxFun.#dimension, ::Base.#+, ::ApproxFun.Infinity{Bool}, ::Tuple{ApproxFun.CosSpace{ApproxFun.PeriodicInterval{Float64}},ApproxFun.SinSpace{ApproxFun.PeriodicInterval{Float64}}}, ::Int64) at ./reduce.jl:46
 in mapfoldl(::ApproxFun.#dimension, ::Function, ::Tuple{ApproxFun.CosSpace{ApproxFun.PeriodicInterval{Float64}},ApproxFun.SinSpace{ApproxFun.PeriodicInterval{Float64}}})
...
```
The same difficulty is encountered calling the test ```include("MultivariateTest.jl")```. 
An issue is to load ```ApproxFun``` before the package ```Polynomials```.

**Comment by dlfivefifty** [comment]
I believe this is a more general Julia bug in v0.5.   When v0.6 is released it should hopefully be fixed
