### ISSUE TITLE
Rename `eltype` for `Fun` and `Domain`

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/ApproxFun.jl#473]
It looks like `Base` uses `eltype` in a way that assumes the argument is an array, so this is a bad override

**Comment by wormell** [comment]
Renaming would also make things clearer for e.g. elements of a 2D domain where you call eltype(eltype(..)) for e.g. operators. I've got the same thing happening in Poltergeist with MarkovMaps.

**Comment by dlfivefifty** [comment]
Now it's `cfstype`
