### ISSUE TITLE
Derivative(Laurent(PeriodicInterval())) is not diagonal.

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaApproximation/ApproxFun.jl#477]

**Comment by dlfivefifty** [comment]
I solved this by having ZeroOperator have bandinds (720,-720).   720 is factorial(6), and was chosen fairly arbitrary (I did factorial in case there's something special about being divisible by a number.)

This requires master on BandedMatrices.jl, to support zero length bandrange.
