### ISSUE TITLE
ApproxFun doesn't show up on the package listing

### ISSUE THREAD

**Issue by wormell** [JuliaApproximation/ApproxFun.jl#496]
Probably not a major issue but: http://pkg.julialang.org/
https://github.com/JuliaCI/PackageEvaluator.jl

It might be due to the tests (http://pkg.julialang.org/logs/ApproxFun_0.5.log) in which case perhaps we should tell PackageEvaluator not to run the tests and see what happens?

**Comment by dlfivefifty** [comment]
It looks like it's there now.
