### ISSUE TITLE
Implement DefiniteIntegral in 2D

### ISSUE THREAD

**Issue by michakraus** [JuliaApproximation/ApproxFun.jl#500]
I am in dire need of a DefiniteIntegral in 2D (to be precise for Chebyshev(0..1)^2). What does it take to implement that? Right now, I get:
```
> S = Chebyshev(0..1)^2
> I = DefiniteIntegral(S)
ERROR: Implement Integral(Chebyshev(【0.0,1.0】)⊗Chebyshev(【0.0,1.0】),1)
```
I had a look at the code and I do not pretend to understand everything, but it seems like this should almost work (I am running with ApproxFun 0.6.1).

**Comment by dlfivefifty** [comment]
The following works (note it's the integral with respect to Lebesgue, not Chebyshev):
```julia
julia> S = Chebyshev(0..1)^2
Chebyshev(【0.0,1.0】)⊗Chebyshev(【0.0,1.0】)

julia> Q = DefiniteIntegral(S[1]) ⊗ DefiniteIntegral(S[2])
KroneckerOperator:Chebyshev(【0.0,1.0】)⊗Chebyshev(【0.0,1.0】)→ConstantSpace⊗ConstantSpace
 1.0  0.0  0.0  -0.333333  0.0  -0.333333  0.0  -0.0  -0.0  0.0  ⋯

julia> f = Fun((x,y) -> exp(-x*cos(y)),S);

julia> Q*f
Fun(ConstantSpace⊗ConstantSpace,[0.677874])

julia> Number(Q*f)
0.6778740675550482

julia> sum(f)
0.6778740675550483
```

I just added the following to the development branch to make your original code work:
```julia
DefiniteIntegral(S::TensorSpace) = DefiniteIntegralWrapper(mapreduce(DefiniteIntegral,⊗,S.spaces))
```

**Comment by dlfivefifty** [comment]
PS I'd recommend not using `I` as a variable, as in Julia it's usually the identity matrix: `zeros(5,5) + I`.

**Comment by dlfivefifty** [comment]
PPS development branch is now Julia v0.6 only, so if you are using Julia v0.5, just add that line

**Comment by michakraus** [comment]
Thanks a lot for the very quick help. This is working well now.
