### ISSUE TITLE
Warning received while executing the first few lines of readme file

### ISSUE THREAD

**Issue by ptoche** [JuliaApproximation/ApproxFun.jl#501]
Just ran the first few lines of code and got a warning. Is it one of those that can be safely ignored? Looks like it is to do with ``Plots``

from https://github.com/JuliaApproximation/ApproxFun.jl

        using ApproxFun
        x = Fun(identity,0..10)
        f = sin(x^2)
        g = cos(x)

        h = f + g^2
        r = roots(h)
        rp = roots(h')

        using Plots
        plot(h)

        WARNING: using Plots.h in module Main conflicts with an existing identifier.

**Comment by dlfivefifty** [comment]
It can be safely ignored, as you can access `Plots.h` by being explicit about the package.

I think the actual issue is that Plots.jl shouldn't be exporting such a short function. @tbreloff

**Comment by ptoche** [comment]
Thanks!
