### ISSUE TITLE
Fast hermits transform?

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaApproximation/ApproxFun.jl#506]
I note that your hermite transform uses gausshermite quadrature. While this is clearly a reliable choice, is there any scope for implementing an N*logN method as described in 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2630232/#!po=88.5000
?
For band limited functions there is a factorization using recursion relation, akin to fft vs basic fft. I don't know it well enough to know how practical it is to implement. Maybe this would sit better in FastTransforms.jl ?

**Comment by dlfivefifty** [comment]
Definitely would be welcomed, but more of an issue for FastTransforms.jl. Can you open an issue there?
