### ISSUE TITLE
Evaluation in broadcast test is not sufficiently deterministic

### ISSUE THREAD

**Issue by RalphAS** [JuliaApproximation/ApproxFun.jl#512]
I noticed that the Julialang automated package tester shows ApproxFun failing ([here](https://pkg.julialang.org/detail/ApproxFun.html)). [Aside: Does this explain #496 ?] The particular test is
```julia
f=Fun(exp)
@test norm(besselj.(1,f)-besselj(1,f)) < 100eps()
```
I ran this test 1000 times on my system, getting a standard deviation of 3.4e-14 and a maximum value of 2.0e-12 (which violates the assertion, as in the run linked above).  Some of this variation is likely due to the use of multithreaded BLAS to do reductions (dot products), but a smaller run with one thread seems consistent with the same distribution. The peak value seems high, since the functions in question are quite smooth.  Perhaps this warrants further study by someone who understands the algorithms. In any case, it is currently a problem for the test suite.

Resetting the RNG with the same seed for each sample almost eliminates the variance; that would be appropriate for the test suite if the behavior is correct (given the algorithm).  It might also be wise to add a note to the documentation pointing out which parts of ApproxFun are non-deterministic.

**Comment by dlfivefifty** [comment]
That's strange as it should be deterministic...

**Comment by dlfivefifty** [comment]
OK I found the culprit: https://github.com/JuliaApproximation/ApproxFun.jl/blob/master/src/Extras/specialfunctions.jl#L455

This looks like a hack, pretty sure it was written by @MikaelSlevinsky 

Is it possible to `srand` but locally? This would be a quick workaround.

**Comment by dlfivefifty** [comment]
I think `xmin` and `xmax` could be precomputed and written out explicitely (that is, the loop becomes `(op,ODE,RHS,growth,xmin,xmax)` for each special function.

**Comment by MikaelSlevinsky** [comment]
Definitely hacky.

Did `chop` change recently? The code becomes errant when `g = chop(imag(f),eps(Float64))` returns a `Fun` with an *empty vector* of coefficients. Maybe at some point in the past it used to return `[0.0]`? With an empty vector, it fails the test `g.coefficients == [0.]` and checks `indmin` and `indmax` instead. But both of those return `-1`, so we end up with two copies of the same boundary condition.

Maybe it would be more robust if we used 4 boundary conditions and solved the problems by least squares?

**Comment by MikaelSlevinsky** [comment]
I don't think it needs to be non-deterministic, but I agree that we should document parts of the code that are/aren't.

**Comment by dlfivefifty** [comment]
Yes, `chop` changed to use the Chebfun `chop`. Note that empty vector of coefficients is allowed and should be checked for. (This is necessary partly because `ZeroSpace` is zero dimensional.)

All of the code should be deterministic for reproducibility.

**Comment by MikaelSlevinsky** [comment]
Ya and `isempty` is a better test:
```julia
julia> using BenchmarkTools

julia> c = Float64[]
0-element Array{Float64,1}

julia> @btime isempty($c)
  1.277 ns (0 allocations: 0 bytes)
true

julia> @btime $c == [0.0]
  30.828 ns (1 allocation: 96 bytes)
false

```

**Comment by dlfivefifty** [comment]
maybe `Fun(sp::Space,cfs::Vector)` should always prune the exactly zero tail, so that a `Fun` is exactly zero if and only if it is empty. 

The issue with this is I'm not sure how it would work for `Fun(sp::Space,cfs::AbstractVector)`: we'd have to override `chop(cfs::SubArray,0)`, etc. to not make a copy.

**Comment by MikaelSlevinsky** [comment]
Just pushed a change to development and now it appears to be back to original behaviour. Still not fully deterministic in case functionals hit the (almost 0) probability eigenfunction.
```julia
julia> using ApproxFun
INFO: Recompiling stale cache file /Users/Mikael/.julia/lib/v0.6/ApproxFun.ji for module ApproxFun.
f = 
julia> f = Fun(exp)
Fun(Chebyshev(【-1.0,1.0】),[1.26607, 1.13032, 0.271495, 0.0443368, 0.00547424, 0.000542926, 4.49773e-5, 3.19844e-6, 1.99212e-7, 1.10368e-8, 5.5059e-10, 2.49797e-11, 1.03911e-12, 3.99195e-14])

julia> norm(besselj.(1,f)-besselj(1,f))
3.699283093820967e-15

julia> norm(besselj.(1,f)-besselj(1,f))
3.699283093820967e-15

julia> norm(besselj.(1,f)-besselj(1,f))
3.699283093820967e-15

end

**Comment by MikaelSlevinsky** [comment]
For future improvement, this shows the non-deterministic aspect. When both endpoints are zeros of the function, a branch in the code chooses points in the domain at random.
```julia
julia> x0 = 3.8317059702075125
3.8317059702075125

julia> x = Fun(identity,Chebyshev(0.0..x0))
Fun(Chebyshev(【0.0,3.8317059702075125】),[1.91585, 1.91585])

julia> besselj(1,x)
Fun(Chebyshev(【0.0,3.8317059702075125】),[0.270774, -0.0130769, -0.289827, 0.0138185, 0.0195805, -0.000758432, -0.000534983, 1.71013e-5, 7.96841e-6, -2.15862e-7  …  4.85169e-10, -1.00349e-11, -2.29877e-12, 4.24892e-14, 8.31472e-15, -1.38666e-16, -2.38389e-17, 4.19586e-19, 3.24347e-20, 4.41558e-21])

julia> besselj(1,x)
Fun(Chebyshev(【0.0,3.8317059702075125】),[0.270774, -0.0130769, -0.289827, 0.0138185, 0.0195805, -0.000758432, -0.000534983, 1.71013e-5, 7.96841e-6, -2.15862e-7  …  8.82107e-19, -6.79489e-19, 5.07243e-19, -3.6425e-19, 2.48974e-19, -1.5946e-19, 9.33279e-20, -4.77717e-20, 1.95533e-20, -4.99985e-21])

julia> besselj(1,x)
Fun(Chebyshev(【0.0,3.8317059702075125】),[0.270774, -0.0130769, -0.289827, 0.0138185, 0.0195805, -0.000758432, -0.000534983, 1.71013e-5, 7.96841e-6, -2.15862e-7  …  2.8209e-18, -2.2894e-18, 1.79309e-18, -1.34603e-18, 9.58754e-19, -6.38115e-19, 3.87162e-19, -2.04995e-19, 8.66246e-20, -2.28281e-20])

```

**Comment by MikaelSlevinsky** [comment]
> maybe Fun(sp::Space,cfs::Vector) should always prune the exactly zero tail, so that a Fun is exactly zero if and only if it is empty.

What about if the first of two functions in a `PiecewiseSpace` is supposed to be empty?

**Comment by dlfivefifty** [comment]
I think probably we want an `iszero(::Fun)`, which is consistent with `roots` warning.
