### ISSUE TITLE
Installing ApproxFun requires ~95MB despite only having ~1MB of code

### ISSUE THREAD

**Issue by ikirill** [JuliaApproximation/ApproxFun.jl#515]
When I install ApproxFun (with `Pkg.checkout`), it results in a directory of about ~95MB, and most of that is taken up by the .git directory (~85MB). This was after running `git gc --aggressive`, which helped reduce this from the original ~120MB. This doesn't seem right, because this package has no binary blobs (except the ipynb's in examples/ maybe?), and all of the code in src is about ~1MB. I found no previous issue on this, and 100MB seems excessive—I suspect this is not intentional.

**Comment by dlfivefifty** [comment]
Not intentional, but I have no idea how to resolve it.

**Comment by RalphAS** [comment]
Poking around in the git object store, I found several large old (Julia v0.3) notebooks, accounting for tens of MB in their compressed state.  We probably have to wait for Pkg3 to avoid getting these with every installation.

**Comment by ikirill** [comment]
Is it an option to move all the notebooks to a different repo and delete them from this repository, including from its history? There seems to be a description of this process here: https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by dlfivefifty** [comment]
Yes, that's a good option: I can create "JuliaApproximation/ApproxFunExamples"

**Comment by ikirill** [comment]
@dlfivefifty The issue is still there: removing the files from the current version with a new commit doesn't remove all the past versions from the repository's history—the files and all their past versions are still there (for example, try checking out a revision before you moved the examples out, like `git checkout 9fd18c`). Currently, using git clone still gives a 111MB directory. That's why I linked to https://help.github.com/articles/removing-sensitive-data-from-a-repository/, that's to remove the files from history too, in an irreversible backwards-incompatible way.

**Comment by dlfivefifty** [comment]
I followed those directions to remove all .ipynb files but it didn't reduce the size.

**Comment by dlfivefifty** [comment]
It also ruined all my tags... I think I need to restore the original version of the repository.

**Comment by dlfivefifty** [comment]
OK I somehow managed to fix all my tags, I think.

I'm not going to touch this again for now.

**Comment by ikirill** [comment]
I got ~10MB when I followed those instructions.

**Comment by dlfivefifty** [comment]
Which files? And how do you preserve the tags?

**Comment by dlfivefifty** [comment]
Maybe you can fix it on a fork, I then clone your fork, and force push back here.

**Comment by RalphAS** [comment]
@ikirill's scheme seems appealing at first glance, but it is a rewrite of git history.  The git man pages say this:

    WARNING! The rewritten history will have different object names for all the objects
    and will not converge with the original branch. You will not be able to easily push and
    distribute the rewritten branch on top of the original branch. Please do not use this
    command if you do not know the full implications ...

    Rebasing (or any other form of rewriting) a branch that others have based work on
    is a bad idea: anyone downstream of it is forced to manually fix their history. [the next]
    section explains how to do the fix from the downstream’s point of view. The real fix,
    however, would be to avoid rebasing the upstream in the first place.

There are 20 forks here on github, and a long list of branches in the main repo, which would all be inconvenienced by this move. The impact on end users is unlikely to be trouble-free. Please check with @tkelman before considering it.

**Comment by tkelman** [comment]
Rewriting history here would destroy the ability of Pkg to install any of the old versions, since they're listed by sha in METADATA and those sha's should not be changed.

**Comment by tkelman** [comment]
You can download a non-git-repo copy of a commit as an archive via github and add that manually to your LOAD_PATH as a short-term way of using the code here with a smaller footprint. Libgit2 doesn't currently support shallow clones, it might support single-branch clones (so you could keep the old branch but have a new separate compact branch going forward) but that would require testing. Pkg3 is planning on supporting working from non-git copies, but I don't know where in the order of features that's going to get implemented.
