### ISSUE TITLE
Weird transformations constructing Fun from Array

### ISSUE THREAD

**Issue by LewisHein** [JuliaApproximation/ApproxFun.jl#539]
Chebyshev approximation is not working well. For example (following the docs):

```julia
s = Chebyshev(0..2pi)
d = [sin(x) for x in 0:.001:2pi]
f = Fun(s, ApproxFun)
f(pi/2) #Result: -0.8660469672458383

p = plot(0:.001:2π, d, label="Array");
plot!(p, f, label="Fun")
```
![bug](https://user-images.githubusercontent.com/12545459/30522393-6b8ac3f8-9b8c-11e7-845e-fab3464db670.png)

Or,
```julia
s = Chebyshev()
d = [x for x in -1:.001:1];
f = Fun(s, ApproxFun.transform(s, d))
f(-.5) #Result: 0.33350000026153737

p = plot(-1:.001:1, d, label="Array");
plot!(p, f, label="Fun")
```
![bug](https://user-images.githubusercontent.com/12545459/30522426-f2fee3d2-9b8c-11e7-9b2e-b8b0146cd6bc.png)

This appears to be a ```x->(-2/pi)*asin(x)``` transformation:
```julia
s = Chebyshev()
d = [x for x in -1:.001:1];
f = Fun(s, ApproxFun.transform(s, sin.(-pi/2*d)))
f(-.5) #Result: -0.5002267077828869

p = plot(-1:.001:1, d, label="Array");
plot!(p, f, label="Fun")
```

![bug](https://user-images.githubusercontent.com/12545459/30522773-f28ad6a8-9b92-11e7-8c42-5beb1e603c7d.png)

But sometimes it's not:
```julia
s = Chebyshev(0..2pi)
d = [sin(x) for x in 0:.001:2pi]
f = Fun(s, ApproxFun.transform(s, sin.(-pi/2*d)))
f(pi/2) #Result: 0.9779447516105816

p = plot(0:.001:2π, d, label="Array");
plot!(p, f, label="Fun")
```
![bug](https://user-images.githubusercontent.com/12545459/30522817-94d3ad22-9b93-11e7-9539-8a31512c294e.png)

**Comment by dlfivefifty** [comment]
You need to follow the docs and evaluate at `points(s, n)` before doing a transform, NOT evenly spaced points.
