### ISSUE TITLE
functions with complex domain

### ISSUE THREAD

**Issue by robzan8** [JuliaApproximation/ApproxFun.jl#544]
Sorry to bother you here, but I couldn't find the answer to this by searching on my own.

Is it possible to use ApproxFun on functions with complex domain?
`julia> x = Fun(identity, Disk(0.0+0im, 1.0))`
`ERROR: MethodError: Cannot convert an object of type ApproxFun.Disk{Complex{Float64}} to an object of type ApproxFun.Space
This may have arisen from a call to the constructor ApproxFun.Space(...), since type constructors fall back to convert methods.
Stacktrace:
 [1] #Fun#94(::Array{Any,1}, ::Type{T} where T, ::ApproxFun.F, ::ApproxFun.Disk{Complex{Float64}}) at .julia\v0.6\ApproxFun\src\Fun\constructors.jl:225
 [2] #Fun#95(::Array{Any,1}, ::Type{T} where T, ::Function, ::ApproxFun.Disk{Complex{Float64}}) at .julia\v0.6\ApproxFun\src\Fun\constructors.jl:226
 [3] ApproxFun.Fun(::Function, ::ApproxFun.Disk{Complex{Float64}}) at .julia\v0.6\ApproxFun\src\Fun\constructors.jl:226`

**Comment by robzan8** [comment]
The function is mostly analytic. Actually, I would like to use ApproxFun to find local maxima and singularities. I'm not even sure ApproxFun is the best tool for the job. Do you have any advice?

**Comment by dlfivefifty** [comment]
You mean analytic apart from isolated singularities? Then a rational approximation would be better. There’s software in Matlab by Trefethen and collaborators, but I’m not aware of Julia versions. (RatFun.jl has the data structures but not the approximation algorithms.)

**Comment by robzan8** [comment]
Exactly, analytic apart from isolated singularities. I have been reading about function approximations the whole day, I think you are right about rational approximations being a good fit. But I need a solution in Julia, I think I'm going to port AAA (the Matlab code seems simple enough).
I have one last question: how do I choose the distribution of the points inside the disk? Is there a good choice, like an extension of the Chebyshev points in 2D?
Thank you very much for your time.
