### ISSUE TITLE
ambiguity in `indices` for `BlockBandedMatrix`

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaApproximation/ApproxFun.jl#545]
For better or for worse Julia v0.6.2 is able to detect an ambiguity between `indices` methods at BlockBandedMatrix.jl:492 and BlockBandedMatrix.jl:499. The ambiguity is that the method on line 492 handles `SubArray{_,_,BB,...} where BB <: BlockBandedMatrix` and either `Block`, `SubBlock`, or `UnitRange` indices, while the method on line 499 handles `BB <: AbstractBlockBandedMatrix` but only `SubBlock{UnitRange{Int}}` indices.

**Comment by JeffBezanson** [comment]
Test log here: https://gist.github.com/ararslan/ae2efe715bbc9357ea0a3f501d30b2b0#file-pkgeval_singularintegralequations_test-log

Suggested method to add:
`indices(::SubArray{T,2,BB<:ApproxFun.BlockBandedMatrix,Tuple{ApproxFun.SubBlock{UnitRange{Int64}},ApproxFun.SubBlock{UnitRange{Int64}}},false})`

**Comment by dlfivefifty** [comment]
I don't see a tag for Julia v0.6.2 so can't test this yet.

Note I'm refactoring BlockBandedMatrix as part of https://github.com/JuliaMatrices/BlockBandedMatrices.jl

so eventually this code will disappear.
