### ISSUE TITLE
empty coefficients for LowRankFun null function

### ISSUE THREAD

**Issue by edljk** [JuliaApproximation/ApproxFun.jl#546]
I do not know if it is on purpose but I was surprised by the empty `Float64` array produced by
```julia
julia> d = PeriodicInterval(0, 1) ^ 2;
julia> f = LowRankFun((x, y) -> 0, d)
LowRankFun on Fourier(【0.0,1.0❫)⊗Fourier(【0.0,1.0❫) of rank 1.
julia> Fun(f)
Fun(Fourier(【0.0,1.0❫)⊗Fourier(【0.0,1.0❫),Float64[])

```

**Comment by edljk** [comment]
Again related to `LowRankFun`, I didn't expect such a complexity for the simple approximation
```julia
julia> f = LowRankFun((x, y) -> x, d)
WARNING: Maximum number of coefficients 1048577 reached in constructing Fun.
etc.
```
Perhaps, there is a better way to proceed..?

**Comment by dlfivefifty** [comment]
For your first question: an empty vector of coefficients is interpreted as zero.

For your second question: it's because you can approximate `x` by Fourier series due to Gibbs phenomenon. If you use `d = Interval(0,1)^2` it will switch to using Chebyshev series.

**Comment by edljk** [comment]
Thanks for the very fast answer and the nice Package!
Oups, I forgot the periodicity gives discontinuity! Perfect, thanks.

**Comment by edljk** [comment]
Just for memory: its seems to me that the `cos` call below could be replaced by its vectorized version `cos.`
https://github.com/JuliaApproximation/ApproxFun.jl/blob/b615605893063be3378323aa609348d45e59403c/src/Spaces/Fourier/Fourier.jl#L172

**Comment by dlfivefifty** [comment]
No you should vectorize on `f`, that is, if `f = Fun(θ - > cos(cos(θ)), CosSpace())` you should not be calling `f([1,2,3])` but call `f.([1,2,3])`.

**Comment by edljk** [comment]
Perfect, sorry for the noise. Thanks.
