### ISSUE TITLE
Finding Discontinuities

### ISSUE THREAD

**Issue by lcw** [JuliaApproximation/ApproxFun.jl#556]
I am using ApproxFun to solve scalar convex conservation laws (see <https://arxiv.org/abs/1605.04473> where we previously used ChebFun) and am really liking it, thanks!

I am not sure if this is the right place for this question.  If not please feel free to close the issue.

One thing I need is to find the points in a domain where a function is discontinuous.  I didn't find an appropriate function provided by ApproxFun so I am currently using this function

```
function jumplocations(f)
  if space(f) isa PiecewiseSpace
    # Double check that the domain components are connected
    @assert all(first.(components(domain(f))[2:end]) -
                last.(components(domain(f))[1:end-1]) .< eps(2000.))

    j = abs.(first.(components(f)[2:end]) - last.(components(f)[1:end-1]))
    ends = last.(components(domain(f))[1:end-1])
    ends[j.>eps(2000.)]
  else
    T = typeof(first(f))
    Array{T}(0)
  end
end
```

If possible, it would be nice to have such a function provided by ApproxFun

I didn't see a lot of documentation on piecewise spaces and also wanted to double check that what I have done is okay.  It seems to work for the simple functions I have tested.

**Comment by dlfivefifty** [comment]
Cool! Do you mind putting together a pull request?
