### ISSUE TITLE
Error in evaluating a Laguerre series?

### ISSUE THREAD

**Issue by kuanxu** [JuliaApproximation/ApproxFun.jl#562]
Was trying to plot a Laguerre series and it seems that `plot` doesn't support Laguerre. So evaluated the series to plot manually. Apparently, the last few values of the series for large abscissas are not correct. Is this necessarily a bug or something inevitable?
```
f = x->exp(-x);
F = Fun(f, Laguerre())
xx = logspace(-5, 5, 20)
vf = F.(xx)
julia > vf
20-element Array{Float64,1}:
  0.99999
  0.999966
  0.999887
  0.999621
  0.998727
  0.995728
  0.985718
  0.95282
  0.85012
  0.579517
  0.159936
  0.00211546
  1.04851e-9
 -1.10905
 -5.94553e31
 -1.97032e59
 -7.25485e83
 -6.20649e107
  0.0
 -1.80074e155
```

**Comment by dlfivefifty** [comment]
This is because Laguerre polynomials blow up.
