### ISSUE TITLE
Bug with DefiniteIntegral in coupled problem

### ISSUE THREAD

**Issue by rveltz** [JuliaApproximation/ApproxFun.jl#571]
Hi,

I come back to you to solve the couple transport problem. $\partial_vu1+\partial_wu_1=0$ on v<0 and $\partial_vu2+\partial_wu_2=0$ on v>0 with the BC $u_1(0,w)-u_2(0,w) = int_0^\infty f(v) u2(v,w-\hat w)dv+int{-\infty}^0 f(v) u1(v,w-\hat w)dv$

```julia
dv1 = Domain(-10..0) 
dv2 = Domain(0..10) 
dw = Domain(-10..10) 
d = UnionDomain((dv1,dv2))*dw 

f = Fun((v,w)->exp(v),UnionDomain((dv1,dv2))*dw)#rate function 
f1 = Fun((v,w)->exp(v),dv1*dw)#r 
f2 = Fun((v,w)->exp(v),dv2*dw)#r 

B1 = DefiniteIntegral()[f1] 
B2 = DefiniteIntegral()[f2] 

A = [rdirichlet(dv1)⊗I+B1 -ldirichlet(dv2)⊗I+B2; 
       Derivative(dv1*dw,[1,0])+Derivative(dv1*dw,[0,1]) 0; 
       0 Derivative(dv2*dw,[1,0])+Derivative(dv2*dw,[0,1])]; 

@time u=\(A,[0;0;0];tolerance=1E-6)
surface(u)
```

I could not code B1 as I would like to (see the latex formula above) but the code complains at the definition of `A`. If I remove `B1,B1` from the definition of `A`, things get computed.

Hopefully, there is an easy fix,

Best regards

Thank you for your help,

Romain

**Comment by dlfivefifty** [comment]
Just to clarify, `rdirichlet(dv1)⊗I` gives a function while `B1` gives a constant. This is desired, right?

**Comment by rveltz** [comment]
This is not desired. I want 
$(B1\cdot u_1)(w) = \int_{-\infty}^0 f(v) u_1(v,w-\hat w)dv$

**Comment by dlfivefifty** [comment]
This works now:
```julia
dv1 = Domain(-10..0)
dv2 = Domain(0..10)
dw = Domain(-10..10)
d  = UnionDomain((dv1,dv2))*dw

S = PiecewiseSpace(Legendre(dv1), Legendre(dv2))*Legendre(dw)


f = Fun((v,w)->exp(v),d)#rate function
f1 = Fun((v,w)->exp(v),dv1*dw)#r
f2 = Fun((v,w)->exp(v),dv2*dw)#r

B1 = DefiniteIntegral(S)[f1]
B2 = DefiniteIntegral(S)[f2]
B3 = (-ldirichlet(Legendre(dv1))+ldirichlet(Legendre(dv2)))⊗eye(Legendre(dw))

Dv = Derivative(S,[1,0])
Dw = Derivative(S,[0,1])

@time u=\([B3+B1+B2;Dv+Dw],
            [0;0];tolerance=1E-6)
```
It's still a bit brittle: it touches a lot of things that need a redesign.

**Comment by rveltz** [comment]
Thank you a lot!

Just to be sure, the boundary condition B3+B1+B2 implies that B1 and B2 are evaluated on the line v=0 ?

**Comment by dlfivefifty** [comment]
Ah, no, in this case `DefiniteIntegral(S)` is the double-integral over the whole rectangle. You probably want something like:
```
S1 = PiecewiseSpace(Legendre(dv1), Legendre(dv2))

f = Fun((v,w)->exp(v),d)#rate function
f1 = Fun(v->exp(v),dv1)#r
f2 = Fun(v->exp(v),dv2)#r

B1 = DefiniteIntegral(S1)[f1]⊗eye(Legendre(dw))
B2 = DefiniteIntegral(S1)[f2] ⊗eye(Legendre(dw))
B3 = (-ldirichlet(Legendre(dv1))+ldirichlet(Legendre(dv2)))⊗eye(Legendre(dw))

Dv = Derivative(S,[1,0])
Dw = Derivative(S,[0,1])

@time u=\([B3+B1+B2; Dv+Dw],
            [0;0];tolerance=1E-6)
```
Though I'm not sure about the $\hat w$ term.

**Comment by rveltz** [comment]
$\hat w$ term is a translation, basically

$u1(0,w+\hat w) - u2(0,w+\hat w) = B1.u1(w)+B2.u2(w)$
 
Is this doable?

**Comment by dlfivefifty** [comment]
A fixed translation?

**Comment by dlfivefifty** [comment]
Doesn't that introduce another singular at w = \hat w?

**Comment by rveltz** [comment]
Yes.

**Comment by rveltz** [comment]
Potentially but other numerical evidence shows it show behaves relatively well.

**Comment by dlfivefifty** [comment]
That's going to be pretty hard to do in ApproxFun I think...

**Comment by rveltz** [comment]
You mean the translation (which I can neglect at first) or the discontinuity at v=0 (which is why I wrote it first as a coupled system)?

**Comment by dlfivefifty** [comment]
The translation. The discontinuity is fine

**Comment by rveltz** [comment]
cool! Thank you.

**Comment by rveltz** [comment]
Arg. This does not work:

```julia
Dv = Derivative(S,[1,0])
Dw = Derivative(S,[0,1])
Wvf = Fun((v,w)-> -w,d)

A = [B3+B1+B2;Dv+Dw -Wvf ]
```

nor `A = [B3+B1+B2;Dv+Wvf*Dw  ]`

**Comment by rveltz** [comment]
Thank you a lot for your help.

Best regards
