### ISSUE TITLE
How are Newton with Neumann conditions supposed to work?

### ISSUE THREAD

**Issue by anriseth** [JuliaApproximation/ApproxFun.jl#572]
(Ref gitter, just in case this is a better place to store this for eternity)

I'm having some issues with applying Neumann boundary conditions to a nonlinear ODE BVP

Using Dirichlet works.
```jl
lhs = -4; rhs = 4
x = Fun(identity, lhs..rhs)
f0 = zero(x)
N = f -> [f(lhs) + lhs ; f(rhs); B^2*f'' + (3*x + 2*f)*f' - f]
f = newton(N, f0)

# f'(lhs) == -0.9999959114806628
```
￼
I tried using Neumann, but it does not work
```jl
N = f -> [f'(lhs) + 1 ; f(rhs); B^2*f'' + (3*x + 2*f)*f' - f]
f = newton(N, f0)

# f'(lhs) == -1.9602345896101728e-16
```

**Comment by dlfivefifty** [comment]
What's `B`?

**Comment by anriseth** [comment]
Ah, sorry. B is a scalar. You can just take B=1

**Comment by dlfivefifty** [comment]
It's fixed on master

**Comment by dlfivefifty** [comment]
PS Just saw you are in Oxford. Let me know if you want to come visit Imperial, it would be good to chat about linking up ApproxFun with Optim.jl in a few places.

**Comment by anriseth** [comment]
> It's fixed on master

Great, thank you :)

> PS Just saw you are in Oxford. Let me know if you want to come visit Imperial, it would be good to chat about linking up ApproxFun with Optim.jl in a few places.

Ah, cool! I'd be up for coming down sometime in April or May. I'll get in touch by e-mail. (It may also be useful to implement a line search for `newton`, if there are cases where it blows up? We are updating the interface of LineSearches with the hope that it can become easier to use with other packages. Ref https://github.com/JuliaNLSolvers/LineSearches.jl/pull/86 )

**Comment by pkofod** [comment]
> Let me know if you want to come visit Imperial, it would be good to chat about linking up ApproxFun with Optim.jl in a few places.

Would love to take part in that discussion, though it will be in digital form from my side!
