### ISSUE TITLE
How to create direct sum of user-specified finite-dimensional space with ApproxFun infinite-dimensional space?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaApproximation/ApproxFun.jl#573]
I want to create the basis `{2-(1-x)^2/2}⊕{(1-x)^2(1+x)P_n^{(2,1)}}` by introducing the least amount of extra machinery.

It is the basis that is the definite integral from `-1..x` of `{(1-x)P_n^{(1,0)}(x)}`. That hasn't been implemented yet:
```julia
julia> using ApproxFun

julia> J = Integral(JacobiWeight(0.0, 1.0, Jacobi(0.0, 1.0)))
ERROR: Implement Integral((1-x)^1.0[Jacobi(0.0,1.0,【-1.0,1.0】)],1)
```
But what if I want to tweak the finite-dimensional basis (so that it's not related by definite integration)?

**Comment by dlfivefifty** [comment]
Could you use `SubSpace(Chebyshev(),1:3)` or `SplineSpace{2}([-1.,0.,1.])`?

**Comment by MikaelSlevinsky** [comment]
I suppose if I want to specify the literal polynomials, then they're their own finite-dimensional space and that's that. (I don't wan't to convert to Chebyshev, so the fact that they span the same space is useless to me.)

**Comment by dlfivefifty** [comment]
Maybe there could be a literal polynomial space where the parameters are templates? 
```julia
struct PolynomialSpace{CFS} <: Space end 

PolynomialSpace{(3//2,1,-1//2)}() 
```

**Comment by MikaelSlevinsky** [comment]
Now can ApproxFun specify not to interlace the two bases in the direct sum? Ideally, the direct sum would start (and finish) with the small finite-dimensional block before indexing the infinite-dimensional block.

Cheers,

Mikael

On Apr 17, 2018, at 3:43 PM, Sheehan Olver <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe there could be a literal polynomial space where the parameters are templates?

struct PolynomialSpace{CFS} <: Space end

PolynomialSpace{(3//2,1,-1//2)}()

**Comment by dlfivefifty** [comment]
You can set the block size so it only has one block.

**Comment by MikaelSlevinsky** [comment]
But then what happens when this derived space is interlaced with another space in an operator on a `PiecewiseSpace`? Wouldn't fixing the block size mean the two finite-dimensional blocks would appear one after the other and only then would there be individual basis-wise interlacing?

In this case, I think it would be natural to interlace one basis element at a time (whether its from the finite-dimensional block or the infinite-dimensional block).

**Comment by dlfivefifty** [comment]
Why do you care how it's interlaced? Blocks are just a way to indicate "importance" of coefficients, and for polynomial bases these should correspond to polynomial degree. 

One could make the case that `(1-x)^a*(1+x)^b` should have zero-sized blocks for the first `floor(Int,a+b)` blocks (since the first coefficient corresponds to a polynomial of degree `a+b`)

**Comment by MikaelSlevinsky** [comment]
You're right: a perfect shuffle preserves symmetry anyway (though I may not be using this approach after all).

**Comment by dlfivefifty** [comment]
Symmetry is preserved under any permutation, provided you apply it both to the domain and range space.

**Comment by MikaelSlevinsky** [comment]
I think this ended up being more of a conversation than an issue. At any rate, I don’t have a use for it anymore.
