### ISSUE TITLE
Laguerre domain is fixed as【0.0,∞❫

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaApproximation/ApproxFun.jl#598]
If Laguerre space stored a domain in the struct, then we could glue it together with Chebyshev on a domain such as `❪-∞,-1.0】∪【-1.0,1.0】∪【1.0,∞❫`.

**Comment by dlfivefifty** [comment]
@zz5016  

In Ray.jl:

- [ ] Add `mappoint(a::Ray, b::Ray, x)` to map a point on ray `a` to one on ray `b`

In Laguerre.jl:

- [ ] `struct Laguerre{T}` -> `struct Laguerre{T<:Real,D<:Ray} <: PolynomialSpace{D,T}` by adding field `domain`
- [ ] Fix `domain(::Laguerre)`
- [ ] Overload `tocanonical(d::Laguerre, x)` and `fromcanonical(d::Laguerre, x)` using `mappoint`.

In test:

- [ ] Add tests for function evaluation on real shifted rays, complex rays, and different orientations

**Comment by dlfivefifty** [comment]
This is fixed.
