### ISSUE TITLE
Code stuck converting Fun from Fourier space to a union space

### ISSUE THREAD

**Issue by bobbielf2** [JuliaApproximation/ApproxFun.jl#602]
When testing the example [here](https://github.com/JuliaApproximation/ApproxFun.jl#periodic-functions), my code got stuck.

1. Generate two Funs

```julia
s = Chebyshev(-π..π)
a = Fun(t-> 1+sin(cos(2t)), s)
L = Derivative() + a
f = Fun(t->exp(sin(10t)), s)
B = periodic(s,0)
uChebyshev = [B;L] \ [0.;f]

s = Fourier(-π..π)
a = Fun(t-> 1+sin(cos(2t)), s)
L = Derivative() + a
f = Fun(t->exp(sin(10t)), s)
uFourier = L\f
```
2. Compare them

```julia
norm( uFourier - uChebyshev ) # Never returns
```
So I looked into the source code a little, it seems to me that the code stalls when it is trying to do

```julia
m = union(uFourier.space,uChebyshev.space)
coefficients(uFourier,m) # Never returns
```

**Comment by dlfivefifty** [comment]
Which version are you on?

**Comment by bobbielf2** [comment]
I am in Julia 0.7

**Comment by dlfivefifty** [comment]
There are some Julia compile bugs where "Never returns" really means "Takes a long time to compile". Can you try waiting (maybe 10 minutes) and see if eventually returns?

I'll check the example on my machine tomorrow.

**Comment by bobbielf2** [comment]
Sure, I'll wait and see what happens.

Another update: I also observed a related strange behavior as follows:

```julia
julia> uChebyshev - uFourier
Fun(Chebyshev(【-3.141592653589793,3.141592653589793】)⨄Fourier(【-3.141592653589793,3.141592653589793❫),[-2.22045e-16, -1.36768, -1.35579e-16, 1.11022e-16, -1.94856e-16, 0.47703, -1.11022e-16, 0.23065, 1.4521e-16, -2.39392e-16  …  -3.00654e-34, 0.0, 0.0, 6.19051e-35, 0.0, 0.0, 1.37553e-34, 0.0, 0.0, 6.38674e-35])

julia> uFourier - uChebyshev # waiting for return
```
While the second one does not return (yet), the first one returns a function whose plot consists of two separate curves: one looks like a zero function, the other looks like the negative of `uChebyshev`.

**Comment by dlfivefifty** [comment]
Thanks I’ll try to fix it tomorrow

**Comment by dlfivefifty** [comment]
Fixed on master.
