### ISSUE TITLE
Add LinearAlgebra to REQUIRE

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaApproximation/ApproxFun.jl#626]
e.g:
```t = Fun(identity,0..1000) 
L = 𝒟^2+2I
```
fails unless 
`using LinearAlgebra`

**Comment by dlfivefifty** [comment]
Thanks! I guess I forgot to update the examples. I’d gladly accept a PR if you have the time.

**Comment by AshtonSBradley** [comment]
I will see what I can do (would be my first ever PR, yikes!)

**Comment by dlfivefifty** [comment]
I don't think you mean add to REQUIRE: one needs to type
```julia
using ApproxFun, LinearAlgebra
```
or better yet put in to the startup.jl file.
