### ISSUE TITLE
Sampling is slow

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaApproximation/ApproxFun.jl#635]
The readme example
https://github.com/JuliaApproximation/ApproxFun.jl#sampling

is very slow, taking several minutes on my i5 laptop. The output is also now different from the readme figure. 

Running

```julia
f = abs(Fun(sin, -5..5))
x = ApproxFun.sample(f,10000)
histogram(x;normed=true)
plot!(f/sum(f))
```

produces the figure:

![screen shot 2018-11-24 at 8 22 13 am](https://user-images.githubusercontent.com/24194258/48958153-3a8fda00-efc2-11e8-87cb-ed07972c0942.png)

**Comment by dlfivefifty** [comment]
I've pushed a fix for the bug. It's still slow due partly to evaluation being slow. I don't have time at the moment to fix it, though it's definitely on the long term plan. (The relevant space is useful for hp-FEM which is a long term goal.)

**Comment by newptcai** [comment]
The example given in the `README.md` takes a long time to finish (didn't have the patience to wait till the end)
```Julia
f = abs(Fun(sin, -5..5))
x = ApproxFun.sample(f,10000)
histogram(x;normed=true)
plot!(f/sum(f))
````

Same thing takes just a few seconds in Mathematica.
````Mathematica
f[x_] := Abs[Sin[x]];
c = Integrate[f[x], {x, -5, 5}];
pdf[x_] := f[x]/c;
dist = ProbabilityDistribution[pdf[x], {x, -5, 5}];
y = RandomVariate[dist, 10^4]
````

**Comment by dlfivefifty** [comment]
This is probably compile time so if you run a second time it’ll be fast. It’s a known performance bug in Julia’s type inference code.

Mathematica probably uses rejection sampling.

**Comment by jishnub** [comment]
This should be fast now (at least it is in the documentation)
