### ISSUE TITLE
bad construction of abs(x) + x

### ISSUE THREAD

**Issue by macd** [JuliaApproximation/ApproxFun.jl#637]
Construction of abs(x) + x where  x = Fun() is broken.  It results in a Fun with 196608 coefficients and, moreover, it is incorrect since it should be 0.0 at x = -1.0 and 2.0 at x = 1.0.  There is a "work-around" by using a anonymous  function, but this bad to, for it results in a Fun with 65536 coefficients.  By way of comparison, Chebfun produces a chebfun with 3 coefficients for abs(x) + x.  Details below: (current master of ApproxFun)

"""
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0-DEV.740 (2018-11-29)
 _/ |\__'_|_|_|\__'_|  |  Commit 2ec5560bc3 (0 days old master)
|__/                   |

julia (v1.1)> using ApproxFun

julia (v1.1)> x = Fun()
Fun(Chebyshev(),[0.0, 1.0])

julia (v1.1)> f = abs(x)
Fun(ApproxFun.ContinuousSpace{Float64,Float64}(ApproxFun.PiecewiseSegment{Float64}([-1.0, -0.0, 1.0])),[1.0, 5.55112e-17, 1.0])

julia (v1.1)> ncoefficients(f)
3

julia (v1.1)> g = abs(x) + x
Fun(ApproxFun.ContinuousSpace{Float64,Float64}(ApproxFun.PiecewiseSegment{Float64}([-1.0, -0.0, 1.0]))⨄Chebyshev(),[1.0, -2.22045e-16, 0.63662, 1.0, 0.0, 1.0, 0.0, -1.78771e-16, 0.424413, 1.78771e-16  …  -7.01265e-14, 0.0, 0.0, 0.0, 0.0, 0.0, 3.50605e-14, 0.0, 0.0, 0.0])

julia (v1.1)> ncoefficients(g)
196608

julia (v1.1)> g(-1.0)
1.0

julia (v1.1)> g(1.0)
1.0

julia (v1.1)> h = Fun(x -> abs(x) + x)
Fun(Chebyshev(),[0.63662, 1.0, 0.424413, -1.42798e-17, -0.0848826, -2.15394e-17, 0.0363783, 1.12106e-17, -0.0202102, 3.8654e-18  …  1.75313e-13, 3.63558e-18, -1.40255e-13, 1.15498e-17, 1.05189e-13, -9.42247e-18, -7.01263e-14, -6.52009e-18, 3.50604e-14, -3.86247e-18])

julia (v1.1)> ncoefficients(h)
65536

julia (v1.1)> h(-1.0)
9.381384558082573e-15

julia (v1.1)> h(1.0)
2.000000000000008

julia (v1.1)>   
"""

**Comment by dlfivefifty** [comment]
Fixed! This came up because now `abs(x)` encodes its continuity in the basis, but there was some missing conversions.
