### ISSUE TITLE
`eigs` no longer used

### ISSUE THREAD

**Issue by MasonProtter** [JuliaApproximation/ApproxFun.jl#638]
In this [documentation example](http://juliaapproximation.github.io/ApproxFun.jl/latest/usage/equations.html#Eigenvalue-Problems-1), the function `eigs` is used which is no longer defined in Julia. I believe it has more or less been replaced by `eigen`, but replacing `eigs` with `eigen` results in an error. Do we have to use `eigvals` and `eigvecs` instead or is there a way to make `eigen` work?

**Comment by dlfivefifty** [comment]
I think you can use ` ApproxFun.eigs ` for now. The eigenvalues code needs to be revamped so it’s not worth updating. 

Also, I believe ` eigen ` replaces ` eig ` where ` eigs ` only gives partial knowledge of eigenvalues.

**Comment by MasonProtter** [comment]
I see, thanks!

**Comment by MasonProtter** [comment]
This can be closed now
