### ISSUE TITLE
Rename SinSpace CosSpace to be consistent with other space constructors

### ISSUE THREAD

**Issue by musm** [JuliaApproximation/ApproxFun.jl#653]
Does it not   make sense to rename `SinSpace`, `CosSpace` to `Sin` and `Cos`,  for consistency with `Hardy,Taylor,Fourier,Laurent`   ?

**Comment by dlfivefifty** [comment]
I'm not sure. The thing about `Fourier`, `Taylor`, etc. is that they really only have one interpretation. `Sin` is more likely to cause conflicts and confusion.

**Comment by musm** [comment]
Or go the other way around and postfix everything with `Space`

**Comment by dlfivefifty** [comment]
No. Sometimes consistency is overrated and doing that leads to less usable code. `CosSpace` and `SinSpace` are fairly specialised so I don't think it is a major issue.
