### ISSUE TITLE
Plotting Fun errors when Fun is generated from a vector of integers

### ISSUE THREAD

**Issue by TSGut** [JuliaApproximation/ApproxFun.jl#659]
There should probably be no difference between generating a Fun from an integer valued vector versus a float valued vector and for almost all operations there is not. However, plotting is broken for integer valued vectors.

A simple snippet that reproduces the error:
```
using ApproxFun, Test, Plots

# initialize a very simple function
g = Fun(Jacobi(0,1), [1.,1.,1.,0.,0.,0.])
f = Fun(Jacobi(0,1), [1,1,1,0,0,0])

# just quickly check that both evaluate correctly
x = rand(-1..1)
@test f(x) ≈ g(x)

# works:
plot(g)
# doesn't work:
plot(f)
```
This is not isolated to the Jacobi basis, it happens for just about any basis I tested.

I suppose one could argue that one shouldn't use integer valued vectors for ApproxFun but then such use should probably be removed from the documentation (e.g. here: http://juliaapproximation.github.io/ApproxFun.jl/stable/usage/spaces.html ).

**Comment by dlfivefifty** [comment]
Please post the output.

Integer coefficients are supposed to be supported, but there are always corner cases. A call to ` float(f.coefficients) ` in the right place should fix it. Want to try making a PR?

**Comment by TSGut** [comment]
The error is different depending on the particular polynomial basis but for the Jacobi basis example above the output is

```
julia> plot(f)
ERROR: MethodError: no method matching plan_ichebyshevtransform(::Array{Int64,1})
Closest candidates are:
  plan_ichebyshevtransform(::Array{D<:DualNumbers.Dual,1}; kind) where D<:DualNumbers.Dual at /home/timon/.julia/packages/ApproxFun/UU55f/src/Extras/dualnumbers.jl:48
  plan_ichebyshevtransform(::AbstractArray{T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64},1}; kind) where T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64} at /home/timon/.julia/packages/FastTransforms/vEjxF/src/chebyshevtransform.jl:87
  plan_ichebyshevtransform(::AbstractArray{T<:Union{Complex{BigFloat}, BigFloat},1}; kind) where T<:Union{Complex{BigFloat}, BigFloat} at /home/timon/.julia/packages/ApproxFun/UU55f/src/Extras/fftGeneric.jl:51
```

As you say putting a conversion to a float valued vector in the right places is probably all that is needed to fix this. I'll see if I can find where it belongs, if I can I'll submit a PR.

**Comment by dlfivefifty** [comment]
I think override ` plan_itransform ` in FastTransforms.jl to call the float version. That may be enough, or you may also need to override ` * ` with the plan to do the conver
