### ISSUE TITLE
Odd behavior when plotting Fun generated with BigFloat precision

### ISSUE THREAD

**Issue by TSGut** [JuliaApproximation/ApproxFun.jl#660]
Funs generated from BigFloats behave as expected when doing function arithmetic but produce odd behavior when being plotted directly. Consider the following example:

```
using Plots,ApproxFun

bigf = Fun(x->x*exp(x),BigFloat(0)..BigFloat(1))
regularf = Fun(x->x*exp(x),0..1)

# give something reasonable (see first and second figure below):
scatter(regularf)
scatter(bigf-regularf)

# gives the expected result AND a mirror image of it (see third figure):
scatter(bigf)
```
The problem is reproduced for different intervals and functions, it's not specific to this example. The fact that bigf-regularf seems to behave correctly suggests to me that this is an error somewhere in the plot generation and not in the actual Fun generation. Any ideas what might be causing this?

![1](https://user-images.githubusercontent.com/34382069/55826938-efa1d980-5b00-11e9-879e-aa30c9533a26.png)
![2](https://user-images.githubusercontent.com/34382069/55826967-fcbec880-5b00-11e9-84f7-94a58fd6a6fd.png)
![3](https://user-images.githubusercontent.com/34382069/55826973-ffb9b900-5b00-11e9-9adc-b68fd75d0b26.png)

**Comment by dlfivefifty** [comment]
Are you sure this isn’t a bug in plots?

**Comment by MikaelSlevinsky** [comment]
I can't reproduce

**Comment by TSGut** [comment]
Which Plots backend are you trying to reproduce on? I just checked and it reproduces consistently on different devices for me on the pyplot() backend (for some reason gr() has been broken for me for a couple days so I can't test on that). If it's backend related it would be a Pots bug presumably.

**Comment by TSGut** [comment]
Scrapping Plots.jl for Makie.jl leads to correct plots, so it must be a Plots.jl bug somewhere as @dlfivefifty suggested. I'll see if they know what might be causing this. Thanks, should be closeable.

**Comment by TSGut** [comment]
Given that both of the following workarounds

```
scatter(x->bigf(x),BigFloat(0),BigFloat(1))
scatter(x->bigf(x),0,1)
```
show no weird behavior even in the pyplot backend, I'm not 100% sure it's a Plots.jl bug after all - it might be related to ApproxFun's method of calling plot() and scatter() for the Funs of that type. I guess this is slightly more involved than I originally anticipated it to be, I'll dig into the calls a bit more when I have the time to see which project this issue belongs under.

**Comment by MikaelSlevinsky** [comment]
I was using GR.
