### ISSUE TITLE
In ApproxFun, Is the chebshev function only limited in [-1,1], or could be expanded to real size such as [a,b]?

### ISSUE THREAD

**Issue by Jiaqi-knight** [JuliaApproximation/ApproxFun.jl#662]
Hello, sir.
I knew the basic chebshev  function can be expanded to  real size such as  [0.3,1].  
My question is:
In ApproxFun Package, how can I make it? 

Thankyou very much!

**Comment by dlfivefifty** [comment]
```julia
Fun(f, a..b)
```
