### ISSUE TITLE
Markdown syntax errors in docs

### ISSUE THREAD

**Issue by thisrod** [JuliaApproximation/ApproxFun.jl#673]
Some error messages appear in the `docs/travis.sh` part of the [Travis log](https://travis-ci.org/JuliaApproximation/ApproxFun.jl/jobs/567112621).  The messages don't give line numbers, so it will take some effort to locate the errors.

One problem is
```
@docs
\(::Operator,::)
```
in library.md.  The docstring for the `\` operator is not included in the manual.  I had a brief look at how `LinearAlgebra` does it, but copying and pasting that didn't work.

**Comment by jishnub** [comment]
This should be fixed now (https://juliaapproximation.github.io/ApproxFun.jl/latest/library/#Operators)
