### ISSUE TITLE
hermite polynomials reproducibility

### ISSUE THREAD

**Issue by lazarusA** [JuliaApproximation/ApproxFun.jl#683]
I'm trying to reproduce the plots for the hermite polynomials. However, I can't go beyond the first ones. For example, why this two examples are not equal? I'm missing some factor, or something?
```
using Plots, ApproxFun
gr()
x = -2:0.01:3
f = Fun(Hermite(), [1,2,3])
plot(x, f.(x), label = "default")
plot!(x, 4x.^2 .-1, label = "wiki") # physicists' Hermite polynomials 
                                    #https://en.wikipedia.org/wiki/Hermite_polynomials
```
<img width="597" alt="Screenshot 2019-11-04 at 17 57 19" src="https://user-images.githubusercontent.com/19525261/68140775-ab5aa880-ff2c-11e9-843d-48eac59f5db5.png">

**Comment by dlfivefifty** [comment]
Why would you expect `H_0(x) + 2 H_1(x) + 3 H_2(x)` to plot the same as just `H_2(x)`?

**Comment by lazarusA** [comment]
actually, my intention is to plot all H_{n}, i.e. H_{0}, H_{1}, H_{2}, H_{3}  and so on, but I'm not getting   how these things are called in this library.

**Comment by dlfivefifty** [comment]
Ah there's no convenience for this so you'll have to do:
```julia
H_0 = Fun(Hermite(), [1.0])
H_1 = Fun(Hermite(), [0,1.0])
H_2 = Fun(Hermite(), [0,0,1.0])
plot(x, H_0.(x))
plot!(x, H_1.(x))
plot!(x, H_2.(x))
```
I'm in the process of revamping the underpinnings of ApproxFun in OrthogonalPolynomialsQuasi.jl, where the following will be as easy as:
```julia
H = Hermite()
plot(x, H[x,1:3])
```
