### ISSUE TITLE
add CITATION.bib

### ISSUE THREAD

**Issue by stevengj** [JuliaApproximation/ApproxFun.jl#691]
Would be nice to add a `CITATION.bib` file containing a bibtex entry for citing ApproxFun.

**Comment by dlfivefifty** [comment]
I normally just cite the github link, does that work or should it be a paper?

I should probably make a JOSS submission but can’t find the time

**Comment by stevengj** [comment]
You should put whatever you prefer people to cite.  e.g. a `@misc` item for the github link.

But I would suggest S. Olver & A. Townsend (2014)?, i.e.
```bib
@inproceedings{Olver2014,
  year = {2014},
  publisher = {{IEEE}},
  author = {Sheehan Olver and Alex Townsend},
  title = {A practical framework for infinite-dimensional linear algebra},
  booktitle = {Proceedings of the 1st Workshop for High Performance Technical Computing in Dynamic Languages -- HPTCDL `14}
}
```
It's usually nicer for you when people cite a paper…

**Comment by dlfivefifty** [comment]
Ok I’ll do your suggestion. (In the U.K. citation count doesn’t seem to matter that much)
