### ISSUE TITLE
Oversampling of oscillatory functions

### ISSUE THREAD

**Issue by ajt60gaibb** [JuliaApproximation/ApproxFun.jl#7]
When I try a highly oscillatory function the IFun constructor oversamples, leaving a large tail of coefficients around machine precision. For instance, 

```
f = IFun(x->sin(400*pi*x),[-1,1]); 
println(length(f.coefficients))
  8193
```

The actual length of the Chebyshev expansion should be a little larger than 400*pi, which is about 1250. The issue is probably in `zerocfsIFun` (I think) because the resolution tolerance does not depend on the function.  Somehow, the tolerance needs to depend on the absolute condition number of evaluating the function. See, for instance, here for the relative condition number: 

http://en.wikipedia.org/wiki/Condition_number#One_variable

A quick estimate of the function's derivative (by a coarse finite difference stencil) suffices in the Chebfun constructor.

**Comment by MikaelSlevinsky** [comment]
I just wrote my own constructor (in [this](https://gist.github.com/MikaelSlevinsky/ef4ff92b9043719fff73) gist) based on the following axiom:

1. the ideal constructor would resolve basis element e_k using exactly k coefficients.

Construction and function evaluation are inextricably linked.

Round-off errors committed during construction are on the order of machine epsilon times the infinity-norm of the condition number of function evaluation on the given domain. Therefore, the mean height of the noise in the coefficients increases linearly with the degree of interpolant used.

This is the result of your code with the axiomatic constructor:
```julia
l = zeros(30);
for j = 1:30
    f = myFun(x->sin(10*j*pi*x),Chebyshev()); 
    l[j] = length(f.coefficients);
end
plot(1:30,l) # using Plots
```
![constructsine](https://cloud.githubusercontent.com/assets/8176037/11534393/6b0417b6-9906-11e5-9a7a-74b5ddb6bf20.png)

**Comment by MikaelSlevinsky** [comment]
As a conjecture that might be a corollary to the axiom 1. above:

- For any constructor based on 1., a reconstruction has exactly the same length.

For instance, this code does not err:
```julia
for i=1:5000
    f = myFun(x->cos(i*acos(x)),Chebyshev())
    f2 = myFun(x->f(x),Chebyshev())
    @assert length(f) == length(f2) == i+1
end
```

**Comment by ajt60gaibb** [comment]
Nick and Jared are just writing a paper on how to chop Chebyshev series.  The code looks pretty simple and could be copied over.

**Comment by dlfivefifty** [comment]
Anyone know if there's licensing issues with "copy MATLAB and rewrite in Julia"?  Is referencing the original source in the file sufficient?

We should probably make sure roots.jl has such a reference.

**Comment by ajt60gaibb** [comment]
I would argue that the rootfinding algorithm in ApproxFun is actually better than the one in Chebfun. :+1:  

Not sure about licensing issues, probably are some...

**Comment by dlfivefifty** [comment]
The license says


Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the University of Oxford nor the names of its 
      contributors may be used to endorse or promote products derived from 
      this software without specific prior written permission.

There’s enough similarity between roots.jl and roots.m that it’s probably worth being on the safe side.  How about this:

	#  Based in part on Chebfun v5's chebfun/@chebteck/roots.m, under the following license:

	# Copyright (c) 2015, The Chancellor, Masters and Scholars of the University 
	# of Oxford, and the Chebfun Developers. All rights reserved.

	#  Redistribution and use in source and binary forms, with or without…


I’m pretty sure that right now roots.m is the only bit of code that was taken directly from Chebfun, but maybe there are others.

**Comment by dlfivefifty** [comment]
Finally fixed!
```julia
julia> Fun(x->sin(400*pi*x),-1..1)|>ncoefficients
1364
```
