### ISSUE TITLE
Invalid call in `roots()` command

### ISSUE THREAD

**Issue by Skinsuit** [JuliaApproximation/ApproxFun.jl#709]
I'm getting an illegal instruction call when attempting to use `roots()` in ApproxFun, in both Julia 1.3.1 and 1.4.2.

> Invalid instruction at 0x7f246ed51416: 0x66, 0x0f, 0x3a, 0x0f, 0xc9, 0x08, 0x48, 0x89, 0xc7, 0x48, 0xf7, 0xdf, 0x66, 0x41, 0x0f

A possible cause: I'm using an older processor, an AMD Phenom II, which apparently doesn't have SSSE3. I've used either the pre-built Julia 1.3.1 or a locally built Julia 1.4.2, per the below issue in the main Julia line, and have had success running just about anything else in Julia. Is there a call to this instruction set from within ApproxFun?

> https://github.com/JuliaLang/julia/issues/35215

> It appears your machines are complaining at a palignr instruction. You can see in that linked webpage that the instruction is marked as "SSSE3", and that its opcode starts with 66 0F 3A 0F.

Luckily I have another computer with a more modern processor which runs `roots()` just fine. 

Full text of dump attached.

[ApproxFunErrorDump.txt](https://github.com/JuliaApproximation/ApproxFun.jl/files/4873113/ApproxFunErrorDump.txt)

**Comment by dlfivefifty** [comment]
That looks like an error in FFTW.jl. I'd suggest trying to come up with a MWE and filing an issue with them.

**Comment by Skinsuit** [comment]
Copy, thanks!
    On Sunday, July 5, 2020, 11:31:25 AM EDT, Sheehan Olver <notifications@github.com> wrote:  
 
 


That looks like an error in FFTW.jl. I'd suggest trying to come up with a MWE and filing an issue with them.
