### ISSUE TITLE
help for equation include time and spaces variable 

### ISSUE THREAD

**Issue by hzgzh** [JuliaApproximation/ApproxFun.jl#710]
HI,
I am looking for the approx tutorial about the one time and two variable,but not found.my question how to solve equations like this,
$$
A\frac{\partial p}{\partial t}+RT\frac{\partial G}{\partial x}=0 \\
\frac{1}{A} \frac{\partial G}{\partial t}+\frac{\partial p}{\partial x}+\frac{\lambda v_b G}{AD}-\frac{\lambda v_b^2p}{2RTD}+\frac{pg\sin \theta}{RT}=0$$
D=0.5;A=$\pi$D^2/4;vb=10;L=60000,t=3000.0,R=520,T=300,p((time(0),0)=0.3,G((time(0),L)=1.37
thanks.

I write script,but have errors:
```
D=0.5
A=2π*D
λ=0.05
L=60e3
p₀=0.3e6
t=3000.0
d=Interval(0.0,t)×Interval(0.0,L)
T=300.0
R=520.0
vb=10.0;
Dₜ = Derivative(d,[1,0])
Dₓ = Derivative(d,[0,1])
f=1.37
 p,g= [    ldirichlet() ⊗ I           I  ⊗     I;
                  I  ⊗  I    rdirichlet() ⊗ I;
                       A*Dₜ             R*T*Dₓ;
     Dₓ-λ*vb^2/(2*R*T*D)*I 1/A*Dₜ+λ*vb/(A*D)*I]

p,G=\(B,[p₀;f;0.0,0.0])
```

**Comment by dlfivefifty** [comment]
3D is not supported yet, unfortunately.

**Comment by hzgzh** [comment]
thank
