### ISSUE TITLE
Volterra Equation

### ISSUE THREAD

**Issue by shane5ul** [JuliaApproximation/ApproxFun.jl#718]
I'm trying to test `ApproxFun` to solve a Volterra integral equation (first kind, convolution) for J(t) over the domain t = [0,5]. I'm modeling my attempt after [this reply](https://github.com/JuliaApproximation/ApproxFun.jl/issues/570#issuecomment-375013189).

The equation is:
$$t = \int_0^t G(t-s) J(s)  ds.$$

As a specific example, when G(t) = 1 + exp(-t), we know the solution J(t) = 1 - 0.5 exp(-0.5 t). This is what I am trying to test.

`d = Interval(0.0, 5.0)`
`G = Fun((t,s) -> 1 + exp(-(t-s)), d^2)`
`V = Volterra(Legendre(d))[LowRankFun(G,d^2)]`
`t = Fun(d)`
`J = V \ t`

The code gives me an reasonable approximation to the expected J(t), but takes a long time to run, and throws the following warning:
`┌ Warning: Maximum length 1000000 reached.`
`└ @ ApproxFunBase /home/sachin/.julia/packages/ApproxFunBase/92sMu/src/Caching/matrix.jl:124`

I am assuming this results in the approximation losing precision. I'm wondering if I can specify a level of acceptable precision to perhaps avoid the warning and speed up the calculation. 

Test of reasonableness:
`J(4.0) = 0.9323323583830545`
`Jth(t) = 1 - 0.5 * exp(-0.5 * t) `
`Jth(4.0) = 0.9323323583816936`

**Comment by dlfivefifty** [comment]
@TSgut do you have code for this?

**Comment by shane5ul** [comment]
OK. So I figured out what I wanted based off [this](https://juliaapproximation.github.io/ApproxFun.jl/v0.4/usage/equations.html#Partial-differential-equations-1).

I can replace the line,
`J = V \  t`

with 

`J = \(V, t; tolerance=1E-6)`

Thanks for putting together this amazing package!

**Comment by MikaelSlevinsky** [comment]
I think the reason it takes so long is because the first row of V is zero, which is fooling the solver's stopping criterion. This works much faster:
```julia
julia> d = Interval(0.0, 5.0)
0.0..5.0

julia> G = LowRankFun((t,s)->1 + exp(-(t-s)), Legendre(d)⊗Legendre(d))
LowRankFun on Legendre(0.0..5.0)⊗Legendre(0.0..5.0) of rank 2.

julia> V = Volterra(Legendre(d))[G]
PlusOperator : Legendre(0.0..5.0) → Jacobi(-1.0,0.0,0.0..5.0)
  0.0                     …   0.0                     ⋱
  6.602695178799658          -1.1089392649145828e-6   ⋱
 -0.8713754278411701         -3.548605647673879e-6    ⋱
  0.34749082375626705        -1.1311180501699051e-5   ⋱
 -0.10795496295757648        -4.116382551235583e-5    ⋱
  0.027291774480038167    …  -0.00017449381120704117  ⋱
 -0.0057963082404171515      -0.0008568605140957986   ⋱
  0.0010592382188864269      -0.004817687452738681    ⋱
 -0.00016965893041834138     -0.030635992610041938    ⋱
  2.4168063836004113e-5      -0.48102748927956784     ⋱
   ⋱                      …    ⋱                      ⋱

julia> W = Conversion(rangespace(V), domainspace(V))*V
TimesOperator : Legendre(0.0..5.0) → Legendre(0.0..5.0)
  3.301347589399829       …  -5.544696324572914e-7   ⋱
  2.865659875479244          -2.328772456294231e-6   ⋱
 -0.2619423020424515         -7.429893074686465e-6   ⋱
  0.11976793039934529        -2.623750300702744e-5   ⋱
 -0.040331594238769156       -0.0001078288183596985  ⋱
  0.010747733119810508    …  -0.0005156771626514199  ⋱
 -0.0023685350107653623      -0.0028372739834172395  ⋱
  0.00044478964423404275     -0.017726840031390308   ⋱
 -7.274543329116863e-5       -0.2558317409448049     ⋱
  1.0534923016216008e-5       0.03322477144640218    ⋱
   ⋱                      …    ⋱                     ⋱

julia> t = Fun(Legendre(d))
Fun(Legendre(0.0..5.0),[2.5, 2.5])

julia> J = W \ t
Fun(Legendre(0.0..5.0),[0.8164169997247783, 0.20865179851381427, -0.08330780732084855, 0.020330475535429337, -0.003574629322519901, 0.0004911520887849317, -5.5371742713505e-5, 5.291935489321408e-6, -4.388797784203547e-7, 3.214513766524584e-8  …  1.0777107214373576e-15, 4.048418189755767e-15, 8.652861088703394e-16, 4.279728434628598e-15, 6.513038389924992e-16, 4.5125963368122556e-15, 4.357639118038485e-16, 4.7470218963306025e-15, 2.1866632725255088e-16, 4.9830243798694225e-15])

julia> @time J = W \ t
  0.335084 seconds (53.44 k allocations: 682.248 MiB, 11.38% gc time)
Fun(Legendre(0.0..5.0),[0.8164169997247783, 0.20865179851381427, -0.08330780732084855, 0.020330475535429337, -0.003574629322519901, 0.0004911520887849317, -5.5371742713505e-5, 5.291935489321408e-6, -4.388797784203547e-7, 3.214513766524584e-8  …  1.0777107214373576e-15, 4.048418189755767e-15, 8.652861088703394e-16, 4.279728434628598e-15, 6.513038389924992e-16, 4.5125963368122556e-15, 4.357639118038485e-16, 4.7470218963306025e-15, 2.1866632725255088e-16, 4.9830243798694225e-15])

julia> J(4.0)
0.9323323583816809

julia> 1-0.5*exp(-0.5*4)
0.9323323583816936

```

**Comment by MikaelSlevinsky** [comment]
You can also drop the first row of zeros:
```julia
julia> @time J = Fun(V[2:end,:]\t, Legendre(d))
  0.055862 seconds (13.36 k allocations: 113.058 MiB, 5.81% gc time)
Fun(Legendre(0.0..5.0),[0.8164169997247782, 0.20865179851381407, -0.08330780732084832, 0.020330475535428955, -0.003574629322519448, 0.0004911520887843347, -5.537174271285912e-5, 5.291935488509693e-6, -4.388797775790328e-7, 3.214513664074439e-8  …  1.8136339813383955e-21, -2.140973203364825e-22, 3.559634326467669e-23, -4.185335367119274e-24, 5.4547632582774175e-25, -5.940834510817128e-26, 6.802408593844243e-27, -5.436417262637901e-28, 9.576933283712982e-29, -4.225803176653981e-29])

julia> J(4.0)
0.9323323583816807

```

**Comment by shane5ul** [comment]
Thanks for the insight, Mikael.

**Comment by TSGut** [comment]
Glad you got it to work. 

I do have code for first kind Volterra equations based on [this](https://arxiv.org/abs/1906.03907) but it's not currently public. So @shane5ul if you need more in that direction and the current functionality doesn't suffice, do let me know and I can send you the snippets to maybe make it work.

**Comment by shane5ul** [comment]
Thanks @TSGut. My present needs are satisfied with existing functionality.

I would appreciate looking at the code underlying the paper, if you have it handy. Don't bother if it is work, though.
