### ISSUE TITLE
a silly question on chebyshev points

### ISSUE THREAD

**Issue by hsianktin** [JuliaApproximation/ApproxFun.jl#721]
Hi, I'm just a beginner in learning numerical analysis. I'm using the textbook _Approximation Theory and Approximation Practice_ by Trefethen. I know it might be a silly question but I really feel a strong passion to ask about it.
I'd like to create the figures in that textbooks using ApproxFun.jl. But at the very beginning I found myself unable to generate Chebyshev points correctly.

The code is
`x = Fun(identity,-1..1);
f = sign(x) - x/2;
S = Chebyshev(-1..1);
grids = points(S,6);
f_grids = f.(grids);
f_chebyshev_grids = Fun(S,ApproxFun.transform(S,f_grids));
plot!(f_chebyshev_grids);
scatter!(grids,f_grids)`
And the standard Chebyshev points are created by
`scatter!([cos(π*j/5) for j in 0:1:5],[f(cos(π*j/5)) for j in 0:1:5])`

The resultant figure is 
![test](https://user-images.githubusercontent.com/31653777/99644622-24ba3000-2a89-11eb-8719-3ba5796d596e.png)

Could you please tell me how the Chebyshev points are determined here? I tried to look at the source code but I didn't get a clue. I'm also new in Julia.

Sincere thanks!

**Comment by hsianktin** [comment]
One of my friend tells me that there're two types of chebyshev points. Can ApproxFun find the approximation of functions evaluated on chebyshev points of type 2 instead of type 1?

**Comment by dlfivefifty** [comment]
Just use FastTransforms.jl with `chebyshevtransform(v, Val(2))`?

**Comment by hsianktin** [comment]
> Just use FastTransforms.jl with `chebyshevtransform(v, Val(2))`?

Many thanks!

**Comment by MikaelSlevinsky** [comment]
The two kinds of Chebyshev points here (and in FastTransforms.jl) are roots. Trefethen's points are first kind extrema, I believe, so the transforms are not supported at the moment. (The first kind extrema are related to second kind roots of a different degree and also include the endpoints.)
