### ISSUE TITLE
ArgumentError: Cannot create infinite Array

### ISSUE THREAD

**Issue by JulesArcher** [JuliaApproximation/ApproxFun.jl#735]
Hi,

I keep getting the error above (with a long detailed list of 23 error dependencies) after executing the example in the doc as follows:

using LinearAlgebra, SpecialFunctions, ApproxFun
x = Fun(identity,-1..1)
f = exp(x)

ArgumentError: Cannot create infinite Array

Array{Int64,1}(::UndefInitializer, ::Infinities.InfiniteCardinal{0})@infarrays.jl:20
pad(::StaticArrays.SArray{Tuple{1},Int64,1,1}, ::Infinities.InfiniteCardinal{0})@helper.jl:232
(::ApproxFunBase.var"#284#285"{Infinities.InfiniteCardinal{0}})(::StaticArrays.SArray{Tuple{1},Int64,1,1})@SumSpace.jl:33

+ MORE....

Can anyone else reproduce this error or know of a fix?

Thanks!

**Comment by dlfivefifty** [comment]
Sorry There was a bad version bump, try
```julia
] pin InfiniteArrays@v0.9
```
I made a PR into the registry to fix this

**Comment by JulesArcher** [comment]
Thanks for the quick reply @dlfivefifty ! That seemed to have fixed the issue...
