### ISSUE TITLE
What should ApproxFun do with roots of periodic functions?

### ISSUE THREAD

**Issue by elecprog** [JuliaApproximation/ApproxFun.jl#741]
Currently if you search for the roots of a periodic function the result, whilst correct, are sometimes somewhat unexpected:

```julia
julia> c = Fun(cos, Fourier())
Fun(Fourier(【0.0,6.283185307179586❫),[-5.622629982202156e-17, 1.2537963267703604e-16, 1.0])

julia> roots(c)
2-element Vector{Float64}:
 -1.5707963267948966
  1.570796326794897
```

In this example one of the roots is outside of the interval [0, 2π) and one of the roots within that interval (namely 3π/2) isn't returned. In general I think it would be preferable if `roots` searches within the 'base' interval and not outside of it. Another option would be to give some sort of 'infinite' vector, but that might unnecessarily overcomplicate things.

**Comment by dlfivefifty** [comment]
just a bug: `roots` is using `-π..π` as the "base interval". A PR fixing this would be appreciated.

**Comment by elecprog** [comment]
The bug seems to reside in [ApproxFunFourier.jl/src/roots.jl](https://github.com/JuliaApproximation/ApproxFunFourier.jl/blob/master/src/roots.jl).

**Comment by dlfivefifty** [comment]
It looks like `tocanonical` is broken:
```julia
julia> tocanonical(Circle(),-im)
-1.5707963267948966
```

In 

https://github.com/JuliaApproximation/ApproxFunFourier.jl/blob/cd406eb7e001223d24865eefc75dc83344425c55/src/Domains/Circle.jl#L46

we probably want to add `mod(..., 2convert(T,π))`
