### ISSUE TITLE
rank of quasimatrices

### ISSUE THREAD

**Issue by freemin7** [JuliaApproximation/ApproxFun.jl#751]
I've been trying to follow along a chebfun workshop where this example came up:
`rank([ 1 sin(x)^2 cos(x)^2])` which evaluates to 2. 

This is also useful to dedacticly demonstrate what a bad basis the monomials are. To be honest i am still somewhat unsure about hcat, vcat, and similar functions in Julia. However i've not been able to reproduce the compuation shown above in ApproxFun.

**Comment by dlfivefifty** [comment]
This is better suited for ContinuumArrays.jl which uses the quasimatrix notation

Your example currently won’t work there either tho

**Comment by freemin7** [comment]
Continous Linear Algebra, as Nick Trefethen calls it, gives rise to really interesting generalizations of discrete algorithms that only work in combination with the machinery of ApproxFun which ContinuumArrays doesn't provide either. 

Is it really more appropriate to reimplement ApproxFun with an ContinuumArrays interface than to implement a ContinuumArrays in ApproxFun if Julia users want/expect feature parity with chebfun?

Since you closed this issue so quickly because it pokes at an underlying question, would opening a new issue about supporting Continous Linear Algebra on ApproxFun things be appreciated?

**Comment by dlfivefifty** [comment]
I don’t know why anyone would expect feature parity as they are completely different packages 

we are moving away from mixed metaphors. ContinuumArrays.jl/ ClassicalOrthogonalPolynomials.jl for quasimatrix (functions-as-vectors) like usage. ApproxFun will move to a more consistent language (functions-as-functions), eg operators will become functions of functions

**Comment by dlfivefifty** [comment]
Ie yes please open a Continuous Linear Agebra issue but in ContinuumArrays.jl
