### ISSUE TITLE
Some of the examples with Fourier returned FFTW cannot create plan in Julia 1.7.2

### ISSUE THREAD

**Issue by ay111** [JuliaApproximation/ApproxFun.jl#766]
I noticed that some examples in the documentation of ApproxFun.jl are not working in Julia 1.7.2. Some of the examples with Fourier returned FFTW cannot create plan in Julia 1.7.2. There is an example on d=Domain(-1..1)^2 but Fun(d) returned error. 
Generally, I think there is need to review examples in the documentation as some returned errors.

**Comment by jishnub** [comment]
This should mostly be fixed now, as we are using `doctests` in the documentation. Please reopen if there are specific examples that don't work.

**Comment by ay111** [comment]
Thanks. It is now working.
