### ISSUE TITLE
Implement weighted Ultraspherical{2} -> Ultraspherical{1} derivatives

### ISSUE THREAD

**Issue by johnbcoughlin** [JuliaApproximation/ApproxFun.jl#778]
[DLMF 18.9.20](https://dlmf.nist.gov/18.9) details a banded recurrence relation for the following operator kind:

```
Derivative(JacobiWeight(1.5, 1.5, Ultraspherical(2))) -> JacobiWeight(.5, .5, Ultraspherical(1)),
```

and of course for steps with larger lambda as well.

I was surprised not to find that in this library. Unless I'm missing something, is there a reason why this wouldn't be included? I can add it if someone can point me to the right place.

**Comment by dlfivefifty** [comment]
This is in ClassicalOrthogonalPolynomials.jl which is the future underpinning of ApproxFun
