### ISSUE TITLE
multivariate function approximation

### ISSUE THREAD

**Issue by benjione** [JuliaApproximation/ApproxFun.jl#805]
I wanted to use this package to approximate multivariate functions, but it seems the package does not support that.

```
f = Fun(Chebyshev()^d, [1])
f(zeros(d)) # working for d=2, hanging for d>2
```
It also seems that already the d=2 case needs much more memory allocation for evaluating the function compared to d=1.

There seem to be older issues on that #538 which are 5 years old. Is this package intended to work on higher dimensions (d>10) or is this not the focus of this package?

Edit: If not, does someone know a package which is made for that? I am trying to move some stuff from matlab to julia, but do not want to rewrite everything.

**Comment by jishnub** [comment]
Have you looked at https://github.com/RJDennis/ChebyshevApprox.jl? It claims to be designed for multivariate functions

**Comment by benjione** [comment]
I am trying to implement the multivariate version for Polynomials (Tensorizer Ntuple of 1:\infty) in ApproxFunBase.jl and will open a pull request once I am finished.
