### ISSUE TITLE
Documentation example on partial differential equation returned error; It has broadcasting issue

### ISSUE THREAD

**Issue by ay111** [JuliaApproximation/ApproxFun.jl#806]
The example on partial differential equation returned error on the line containing **f = exp.(-10(x+0.3)^2-20(y-0.2)^2)  # use broadcasting as exp(f) not implemented in 2D** . Hence subsequent lines of code were not evaluated. This may be due to broadcasting issue.

**Comment by jishnub** [comment]
This should be solved now on `ApproxFunBase` v0.7.2
