### ISSUE TITLE
cumsum(Fun(Fourier(),[1,0,1]))(0.1)=0.1??

### ISSUE THREAD

**Issue by awegawegw** [JuliaApproximation/ApproxFun.jl#807]
cumsum(Fun(Fourier(),[1,0,1]))(0.1)=0.10000000000000002 (should be about 0.2)

It seems that when f0!=0, all the cos are not integrated properly (not integrated at all??).

cumsum(Fun(Fourier(),[1,0,0]))(0.1)=0.10000000000000002 works
cumsum(Fun(Fourier(),[0,0,1]))(0.1)=0.09983341664682817 works
cumsum(Fun(Fourier(),[1,1,0]))(0.1)=0.10499583472197431 works
cumsum(Fun(Fourier(),[1,1,1]))(0.1)=0.10499583472197431 again wrong.

Version: 0.13.8
Julia Version 1.8.0

**Comment by jishnub** [comment]
This should be fixed now
```julia
julia> f(0.1)
0.1998334166468282

julia> cumsum(Fun(Fourier(),[1,0,1]))(0.1)
0.1998334166468282
```
