### ISSUE TITLE
Add the option to specify the number of coefficients

### ISSUE THREAD

**Issue by ufechner7** [JuliaApproximation/ApproxFun.jl#886]
I currently use this code:
```
f = Fun(discrete_signal, Chebyshev(Interval(t1[1],t1[end])))
f1 = Fun(Chebyshev(Interval(t1[1],t1[end])), coefficients(f)[1:5])
```
to approximate the function discrete_signal with a Chebyshev function using 5 coefficients. That is a waste of cpu cycles, first to calculate thousends of coefficients just to through most of them away. Please add an option to specify the max number of coefficients.

**Comment by dlfivefifty** [comment]
` Fun(f, sp, n) `

**Comment by ufechner7** [comment]
Nice!

Is this documented anywhere?
